import qrcode from '../../vendor/qrcode-generator.mjs';
import { $, $$, esc, setButtonBusy, toast } from '../ui.js?v=20260902-phase3';

const labels={show_shine:'Show & Shine',best_exhaust:'Nejlepší výfuk'};
const stateLabels={idle:'Čeká na spuštění',live:'Hodnocení běží',paused:'Hodnocení pozastaveno',closed:'Hodnocení uzavřeno',published:'Výsledky zveřejněny'};
const storagePrefix='e36United.memberLiveMode.v2';
const criteria={overall:'Celkový dojem',condition:'Stav a zpracování',cohesion:'Sladění a dotaženost',originality:'Originalita a nápad'};

export function createMemberLive({apiBaseUrl,apiRequest,apiRequestForm,apiRequestBlob,openSection,setLiveMode,getAccountId=()=>'',getRegistrationCar=()=>null,getPrivateCarPhotoUrl=async()=>''}){
  let payload=null,liveStatus=null,requestState='idle',activeView='program',programDay='',judgeEntryId='',pollTimer=0,pollFailures=0,lastStateSignature='',bound=false,modeActive=false,entryOpener=null,overlayOpener=null,mediaGeneration=0,fileSequence=0;
  const objectUrls=new Map(),judgeDrafts=new Map(),judgeFiles=new Map(),galleryFiles=[];
  const root=()=>document.querySelector('[data-member-live-mode]');
  const entryDialog=()=>document.querySelector('[data-member-live-entry]');
  const qrDialog=()=>document.querySelector('[data-live-qr-dialog]');
  const isOpen=()=>modeActive&&!root()?.hidden;
  const accountId=()=>String(getAccountId()||'').replace(/[^a-z0-9_-]/gi,'_');
  const storageKey=eventId=>`${storagePrefix}.${accountId()}.${String(eventId||'').replace(/[^a-z0-9_-]/gi,'_')}`;
  const rememberedEvent=eventId=>{try{return !!accountId()&&localStorage.getItem(storageKey(eventId))==='1'}catch{return false}};
  function rememberEvent(eventId,value){try{if(!accountId()||!eventId)return;value?localStorage.setItem(storageKey(eventId),'1'):localStorage.removeItem(storageKey(eventId))}catch{}}
  function releaseSelection(item){if(item?.url){URL.revokeObjectURL(item.url);item.url=''}}
  function clearSelections(){galleryFiles.splice(0).forEach(releaseSelection);for(const items of judgeFiles.values())items.forEach(releaseSelection);judgeFiles.clear()}
  function releaseMedia(){mediaGeneration+=1;root()?.querySelectorAll('img[src^="blob:"]').forEach(image=>image.remove());for(const url of objectUrls.values())URL.revokeObjectURL(url);objectUrls.clear();clearSelections()}
  async function imageFor(path,key){if(!path)return '';if(objectUrls.has(key))return objectUrls.get(key);const generation=mediaGeneration;try{const blob=await apiRequestBlob(path),url=URL.createObjectURL(blob);if(generation!==mediaGeneration||!modeActive){URL.revokeObjectURL(url);return ''}objectUrls.set(key,url);return url}catch{return ''}}
  const previewable=file=>['image/jpeg','image/png','image/webp'].includes(file?.type);
  function addFiles(target,fileList,max=8){for(const file of [...fileList||[]]){if(target.length>=max)break;if(target.some(item=>item.file.name===file.name&&item.file.size===file.size&&item.file.lastModified===file.lastModified))continue;target.push({id:`live-file-${++fileSequence}`,file,url:previewable(file)?URL.createObjectURL(file):'',status:'ready',error:''})}}
  const fileState=item=>item.status==='uploading'?'Odesílám…':item.status==='error'?(item.error||'Odeslání selhalo · zkus znovu'):'Připraveno';
  function previewsMarkup(items,removeAttribute){return items.length?items.map(item=>`<figure class="live-upload-preview" data-upload-state="${esc(item.status)}">${item.url?`<img alt="Náhled ${esc(item.file.name)}" src="${esc(item.url)}">`:'<span>Náhled není dostupný</span>'}<figcaption><b>${esc(item.file.name)}</b><small>${esc(fileState(item))}</small></figcaption><button aria-label="Odebrat ${esc(item.file.name)}" ${removeAttribute}="${esc(item.id)}" ${item.status==='uploading'?'disabled':''} type="button">×</button></figure>`).join(''):''}
  function renderGalleryPreviews(){const target=$('[data-live-upload-previews]');if(target)target.innerHTML=previewsMarkup(galleryFiles,'data-live-remove-gallery-file')}
  function renderJudgePreviews(form,entryId){const target=form?.querySelector('[data-live-judge-previews]');if(target)target.innerHTML=previewsMarkup(judgeFiles.get(entryId)||[],'data-live-remove-judge-file')}

  function navState(){
    const active=!!(liveStatus&&liveStatus!==false),copy=document.querySelector('[data-live-nav-copy]');
    const text=active?`United ${liveStatus.year} · aktivní`:requestState==='error'?'Stav nedostupný':liveStatus===false?'Nyní neaktivní':'Načítám stav…';
    $$('[data-member-section="live"],[data-main-member-section="live"]').forEach(button=>{button.classList.toggle('is-live',active);button.classList.toggle('is-disabled',liveStatus===false);button.classList.toggle('is-error',requestState==='error');button.title=active?'Spustit aktuální UNITED LIVE':liveStatus===false?'UNITED LIVE teď není aktivní':'Ověřit dostupnost UNITED LIVE'});
    if(copy)copy.textContent=text;
  }
  function showEntry(opener=document.activeElement){entryOpener=opener;const dialog=entryDialog();if(!dialog)return;dialog.hidden=false;requestAnimationFrame(()=>dialog.querySelector('[data-live-entry-confirm]:not([hidden]),[data-live-entry-retry]:not([hidden]),[data-live-entry-cancel]')?.focus())}
  function closeEntry({restore=true}={}){const dialog=entryDialog();if(dialog)dialog.hidden=true;if(restore)entryOpener?.focus?.({preventScroll:true});entryOpener=null}
  function renderEntry(){
    const dialog=entryDialog();if(!dialog||dialog.hidden)return;
    const title=$('[data-live-entry-title]',dialog),copy=$('[data-live-entry-copy]',dialog),state=$('[data-live-entry-state]',dialog),confirm=$('[data-live-entry-confirm]',dialog),retry=$('[data-live-entry-retry]',dialog);
    if(requestState==='loading'||requestState==='idle'){title.textContent='Přepnout do UNITED LIVE?';copy.textContent='Otevře se režim pro celý víkend. Zpět do portálu se vrátíš přes menu Více.';state.textContent='Ověřuji potvrzený stav na serveru…';confirm.hidden=true;retry.hidden=true}
    else if(requestState==='active'){title.textContent='Přepnout do UNITED LIVE?';copy.textContent='Otevře se režim pro celý víkend. Zpět do portálu se vrátíš přes menu Více.';state.textContent=`United ${payload.event.year} je aktivní${payload.event.venue?` · ${payload.event.venue}`:''}.`;confirm.hidden=false;retry.hidden=true}
    else if(requestState==='inactive'){title.textContent='UNITED LIVE teď není aktivní.';copy.textContent='Běžný členský portál zůstává dostupný.';state.textContent='Server nepotvrdil žádný aktivní LIVE ročník.';confirm.hidden=true;retry.hidden=true}
    else{title.textContent='Stav UNITED LIVE se nepodařilo načíst.';copy.textContent='Zkus znovu načíst potvrzený serverový stav.';state.textContent='Spojení nebo autorizovaný požadavek selhal.';confirm.hidden=true;retry.hidden=false}
  }
  function normalizeView(view){if(view==='now'||view==='program')return'program';if(view==='rating'||view==='showshine')return'showshine';return view==='photos'?'photos':'program'}
  function setView(view,{focus=false}={}){activeView=normalizeView(view);$$('[data-live-view]').forEach(node=>{const active=node.dataset.liveView===activeView;node.hidden=!active;node.classList.toggle('is-active',active)});$$('[data-live-tab]').forEach(button=>{const active=button.dataset.liveTab===activeView;button.classList.toggle('is-active',active);button.setAttribute('aria-current',active?'page':'false')});if(activeView==='photos')renderGallery();if(focus)root()?.querySelector(`[data-live-view="${activeView}"] h2`)?.focus({preventScroll:true})}
  function activeDiscipline(){return Object.values(payload?.states||{}).find(item=>['live','paused'].includes(item.status)&&item.entry)||null}
  function currentVote(entryId){return payload?.votes?.find(item=>item.entryId===entryId)?.score||null}
  function qrMarkup(){let svg='';try{if(payload?.me?.qrPayload){const qr=qrcode(0,'M');qr.addData(payload.me.qrPayload,'Byte');qr.make();svg=qr.createSvgTag({cellSize:8,margin:8,scalable:true})}}catch{}return svg}
  function openQr(opener=document.activeElement){overlayOpener=opener;const dialog=qrDialog(),panel=$('[data-live-qr-content]',dialog);if(!dialog||!panel)return;const svg=qrMarkup();panel.innerHTML=svg||'<p>QR kód zatím není dostupný.</p>';dialog.hidden=false;dialog.querySelector('[data-live-qr-close]')?.focus({preventScroll:true})}
  function closeQr(){const dialog=qrDialog();if(dialog)dialog.hidden=true;overlayOpener?.focus?.({preventScroll:true});overlayOpener=null}
  function toggleMore(force){const menu=$('[data-live-more-menu]'),button=$('[data-live-more-toggle]');if(!menu||!button)return;const open=force??menu.hidden;menu.hidden=!open;button.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('button')?.focus({preventScroll:true})}
  function programItems(){const items=payload?.program||[],days=[...new Set(items.map(item=>item.day))];if(!days.includes(programDay))programDay=days[0]||'';return{items,days}}
  function currentProgramMarkup(){const item=payload?.now?.current||payload?.now?.next,current=activeDiscipline(),hasProgram=(payload?.program||[]).some(row=>row.status!=='cancelled');return `<section class="member-live-home"><div class="member-live-carwash" data-live-member-car-media><span class="live-eyebrow">UNITED ${esc(payload?.event?.year||'')}</span><h1>${esc(item?.title||'UNITED LIVE.')}</h1><p>${item?`${payload.now?.current?'Právě teď':'Následuje'} · ${esc(item.startsAt.slice(11,16))}${item.venue?' · '+esc(item.venue):''}`:hasProgram?'Program United je zveřejněný níže.':'Program zatím není zveřejněný.'}</p></div><div class="member-live-quick"><button class="live-primary" data-live-open-qr type="button"><span>▦</span>Otevřít QR kód</button><button data-live-tab-direct="photos" type="button"><span>＋</span>Přidat fotku</button><button data-live-open-votes type="button"><span>★</span>Moje hlasy</button></div>${current?.entry?`<article class="member-live-current" data-live-current-card><span data-live-current-image></span><div><small>${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</small><strong>${esc(current.entry.car.nickname||current.entry.car.model)}</strong><p>${esc(current.entry.member.name)} · ${esc(current.entry.car.model)}</p>${current.status==='live'?`<button data-live-rate="${esc(current.discipline)}" type="button">Hodnotit</button>`:'<em>Dočasně pozastaveno</em>'}</div></article>`:''}</section>`}
  async function hydrateProgramImages(target,current){
    const car=getRegistrationCar(),photoId=car?.photos?.[0]?.id,hero=target.querySelector('[data-live-member-car-media]');
    if(photoId&&hero){try{const url=await getPrivateCarPhotoUrl(photoId);if(hero.isConnected&&url)hero.style.setProperty('--live-car-image',`url("${String(url).replace(/["\\]/g,'\\$&')}")`)}catch(error){console.warn('LIVE registration car photo unavailable',error)}}
    if(current?.entry?.imageUrl){const slot=target.querySelector('[data-live-current-image]'),url=await imageFor(current.entry.imageUrl,`entry-${current.entry.id}`);if(slot?.isConnected&&url)slot.outerHTML=`<img alt="${esc(current.entry.car.model)}" src="${url}">`}
  }
  async function renderProgram(){
    const target=$('[data-live-program]');if(!target||!payload?.active)return;
    const {items,days}=programItems(),current=activeDiscipline();
    const schedule=days.length?`<nav class="live-program-days" aria-label="Dny programu">${days.map(day=>`<button class="${day===programDay?'is-active':''}" data-live-day="${esc(day)}" type="button">${new Date(day+'T12:00:00').toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'numeric'})}</button>`).join('')}</nav><div class="live-program-list">${items.filter(item=>item.day===programDay).map(item=>`<article class="live-program-item ${payload.now?.current?.id===item.id?'is-current':payload.now?.next?.id===item.id?'is-next':''} ${item.status==='cancelled'?'is-cancelled':''}"><time>${esc(item.startsAt.slice(11,16))}${item.endsAt?'–'+esc(item.endsAt.slice(11,16)):''}</time><div><strong>${esc(item.title)}</strong><p>${[item.venue,item.description].filter(Boolean).map(esc).join(' · ')}</p></div>${item.status!=='scheduled'?`<em>${item.status==='cancelled'?'ZRUŠENO':'ZMĚNA'}</em>`:''}</article>`).join('')}</div>`:'<p class="live-empty">Program zatím není zveřejněný.</p>';
    target.innerHTML=`${currentProgramMarkup()}<section class="member-live-schedule"><div class="member-live-section-head"><span>PROGRAM</span><h2 tabindex="-1">Co se děje.</h2></div>${schedule}</section>`;
    await hydrateProgramImages(target,current);
  }
  function disciplineSummary(){return `<div class="live-discipline-switch" role="group" aria-label="Disciplíny">${['show_shine','best_exhaust'].map(discipline=>{const state=payload?.states?.[discipline]||{status:'idle'};return `<button class="${activeDiscipline()?.discipline===discipline?'is-active':''}" data-live-discipline="${discipline}" type="button"><span>${esc(labels[discipline])}</span><small>${esc(stateLabels[state.status]||state.status)}</small></button>`}).join('')}</div>`}
  function scoreButtons({name,value,attribute='data-live-judge-score'}){return `<input name="${name}" type="hidden" value="${value||''}"><div class="live-score live-score--judge">${Array.from({length:10},(_,index)=>`<button ${attribute}="${index+1}" data-live-judge-criterion="${name}" aria-pressed="${Number(value)===index+1}" class="${Number(value)===index+1?'is-selected':''}" type="button">${index+1}</button>`).join('')}</div>`}
  function judgeForm(entry){const saved=payload?.judgeHistory?.find(item=>item.entryId===entry.id)||{},draft=judgeDrafts.get(entry.id)||{},scores={...(saved.scores||{}),...(draft.scores||{})},note=draft.note??saved.note??'',identity=entry.member?.name||'auto',files=judgeFiles.get(entry.id)||[];return `<form class="live-judge-form" data-live-judge="${esc(entry.id)}"><span class="live-eyebrow">POROTA · ${saved.submitted?'ULOŽENO':'ROZEPSÁNO'}</span><h4>${esc(entry.car?.nickname||entry.car?.model||'Hodnocení')}</h4>${Object.entries(criteria).map(([key,label])=>`<fieldset><legend>${label}</legend>${scoreButtons({name:key,value:scores[key]})}</fieldset>`).join('')}<details><summary>Poznámka a fotografie</summary><textarea name="note" maxlength="1000" rows="3" placeholder="Interní poznámka poroty (volitelné)">${esc(note)}</textarea><label class="live-file"><span>Interní fotografie auta</span><input accept="image/jpeg,image/png,image/webp" capture="environment" multiple name="judgePhoto" type="file"><small>Vyber další fotografie; před odesláním je můžeš jednotlivě odebrat.</small></label><div class="live-upload-previews" data-live-judge-previews>${previewsMarkup(files,'data-live-remove-judge-file')}</div>${saved.photos?.length?`<div class="live-judge-photos">${saved.photos.map(photo=>`<span data-live-judge-photo="${esc(photo.imageUrl)}" data-live-judge-photo-key="judge-${esc(photo.id)}">Načítám foto…</span>`).join('')}</div>`:''}</details><p class="live-form-error" data-live-judge-error role="status"></p><div class="live-judge-actions"><button class="member-secondary" data-judge-draft type="submit">Uložit koncept</button><button class="live-primary" data-judge-submit type="submit">Uložit hodnocení „${esc(identity)}“</button></div></form>`}
  async function hydrateJudgePhotos(target){for(const slot of target.querySelectorAll('[data-live-judge-photo]')){const url=await imageFor(slot.dataset.liveJudgePhoto,slot.dataset.liveJudgePhotoKey);if(slot.isConnected&&url)slot.outerHTML=`<img alt="Interní dokumentační fotografie auta" src="${url}">`}}
  function ratingCard(current){if(!current?.entry)return '<p class="live-empty">Až organizátor představí auto, hodnocení se otevře tady.</p>';const own=current.entry.memberId===payload.me?.memberId,eligible=payload.me?.eligible&&!own,currentScore=currentVote(current.entry.id),details=[current.entry.member.name,current.entry.car.model,current.entry.car.body].filter(Boolean).map(esc).join(' · ');return `<article class="live-rating-card"><div class="live-rating-media">${current.entry.imageUrl?'<span data-live-rating-image></span>':'<span class="live-rating-fallback">E36 UNITED</span>'}</div><div class="live-rating-content"><span class="live-eyebrow">${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</span><h3>${esc(current.entry.car.nickname||current.entry.car.model)}</h3><p>${details}</p>${eligible&&current.status==='live'?`<form data-live-vote="${esc(current.entry.id)}"><p>Celkový dojem · 1–10</p>${scoreButtons({name:'score',value:currentScore,attribute:'data-live-score'})}<button class="live-primary" type="submit">${currentScore?'Upravit hlas':'Uložit hlas'}</button></form>`:`<p class="live-empty">${own?'Vlastní auto nemůžeš hodnotit.':!payload.me?.reservation||!payload.me?.eligible?'Hlasování vyžaduje schválenou účast.':'Hodnocení teď nepřijímá hlasy.'}</p>`}</div>${payload.me?.judge&&current.discipline==='show_shine'&&!own?judgeForm(current.entry):''}</article>`}
  function historyMarkup(current){const votes=payload?.votes||[],judgeRows=payload?.judgeHistory||[],selected=judgeRows.find(item=>item.entryId===judgeEntryId),currentId=current?.entry?.id;return `<section class="live-history" data-live-vote-history><span class="live-eyebrow">MOJE HLASY</span>${votes.length?votes.map(item=>`<article><span>${esc(labels[item.discipline])} · ${esc(item.nickname||item.model)}<small>${esc(item.memberNickname||item.name)}</small></span><strong>${item.score}/10</strong></article>`).join(''):'<p>Zatím nemáš uložený hlas.</p>'}</section>${payload.me?.judge?`<section class="live-history"><span class="live-eyebrow">MOJE HODNOCENÍ POROTY</span>${judgeRows.length?judgeRows.map(item=>`<article><span>${esc(item.car.nickname||item.car.model)}<small>${item.submitted?'Uloženo':'Rozepsáno'} · ${item.photos.length} foto</small></span>${item.memberId===payload.me.memberId?'<strong>Vlastní auto</strong>':`<button data-live-judge-history="${esc(item.entryId)}" type="button">Otevřít</button>`}</article>`).join(''):'<p>Zatím žádné hodnocení.</p>'}</section>${selected&&selected.entryId!==currentId&&selected.memberId!==payload.me.memberId?judgeForm({id:selected.entryId,car:selected.car,member:selected.member}):''}`:''}`}
  function resultRows(items,type,discipline){const sorted=type==='jury'?[...items].sort((a,b)=>(a.juryRank??999)-(b.juryRank??999)):items;return sorted.map(item=>{const jury=type==='jury',value=jury?item.jury?.average:item.average,count=jury?item.jury?.judges:item.votes,rank=jury?item.juryRank:item.publicRank;return `<article><span>${rank?`${rank}. `:''}${esc(item.nickname||item.model)}<small>${esc(labels[discipline])} · ${jury?'porota':'publikum'}</small></span><strong>${value==null?'—':`${value} · ${count}`}</strong></article>`}).join('')}
  function resultsMarkup(){const groups=payload?.results||{};return Object.keys(groups).length?`<details class="live-results"><summary>Zveřejněné výsledky</summary>${Object.entries(groups).map(([discipline,items])=>`<section class="live-history">${resultRows(items,'public',discipline)}${discipline==='show_shine'?resultRows(items,'jury',discipline):''}</section>`).join('')}</details>`:''}
  async function hydrateRatingImage(target,current){const slot=target.querySelector('[data-live-rating-image]');if(!slot||!current?.entry?.imageUrl)return;const url=await imageFor(current.entry.imageUrl,`rating-${current.entry.id}`);if(slot.isConnected&&url)slot.outerHTML=`<img alt="${esc(current.entry.car.nickname||current.entry.car.model||'Hodnocené auto')}" src="${url}">`}
  function renderShowShine(){const target=$('[data-live-showshine]');if(!target||!payload?.active)return;const current=activeDiscipline();target.innerHTML=`<div class="member-live-section-head"><span>SOUTĚŽE</span><h2 tabindex="-1">Show &amp; Shine.</h2></div>${disciplineSummary()}${ratingCard(current)}${historyMarkup(current)}${resultsMarkup()}`;void Promise.all([hydrateJudgePhotos(target),hydrateRatingImage(target,current)])}
  function renderGallery(){const target=$('[data-live-gallery]');if(!target)return;const status={pending:'Čeká na schválení',approved:'Schváleno',rejected:'Nevybráno do galerie'},own=payload?.ownUploads?.length?`<section class="member-live-uploads"><span class="live-eyebrow">MOJE NAHRANÉ FOTKY</span>${payload.ownUploads.map(item=>`<p><span>${esc(item.caption||'Fotografie bez popisku')}</span><b data-status="${esc(item.status)}">${esc(status[item.status]||item.status)}</b></p>`).join('')}</section>`:'',gallery=payload?.gallery?.length?payload.gallery.map(item=>`<figure><img alt="${esc(item.caption||'Fotografie z United')}" loading="lazy" src="${esc(apiBaseUrl+item.imageUrl)}"><figcaption>${esc(item.caption||'United LIVE')}</figcaption></figure>`).join(''):'<p class="live-empty">Schválené fotografie tohoto ročníku se objeví tady.</p>';target.innerHTML=own+`<div class="member-live-gallery-grid">${gallery}</div>`}
  function updateConnection(offline=false){const connection=$('[data-live-connection]');if(!connection)return;connection.dataset.state=offline?'offline':'online';connection.title=offline?'Spojení kolísá, zobrazuji poslední potvrzený stav.':'Online · živý stav';connection.setAttribute('aria-label',connection.title)}
  function render(){const copy=$('[data-live-event-copy]'),app=$('[data-live-app]'),error=$('[data-live-error]');if(copy)copy.textContent=payload?.active?`United ${payload.event.year} · člen`:requestState==='error'?'Stav nedostupný':'LIVE není aktivní';if(error)error.hidden=requestState!=='error';if(app)app.hidden=!payload?.active||!modeActive;navState();renderEntry();if(!payload?.active||!modeActive){stopPolling();return}void renderProgram();renderShowShine();renderGallery();renderGalleryPreviews();setView(activeView);schedulePolling()}
  async function load(){requestState='loading';renderEntry();try{const next=await apiRequest('/api/live');payload=next;liveStatus=next.active?next.event:false;requestState=next.active?'active':'inactive';pollFailures=0;lastStateSignature=JSON.stringify(next.states||{});if(!next.active&&modeActive){exitMode({navigate:true,clearChoice:true});toast('UNITED LIVE byl ukončen. Vracíme tě do portálu.')}updateConnection(false);render();return next}catch(error){requestState='error';console.warn('UNITED LIVE unavailable',error);updateConnection(true);render();return null}}
  async function probe(){try{const state=await apiRequest('/api/live/state');liveStatus=state.active?state.event:false;requestState=state.active?'active':'inactive';navState();return state}catch(error){requestState='error';console.warn('UNITED LIVE state unavailable',error);navState();return null}}
  async function requestEntry({opener=document.activeElement}={}){showEntry(opener);requestState='loading';renderEntry();const next=await load();if(!next?.active)return false;if(rememberedEvent(next.event.id)){enterMode({remember:false});return true}renderEntry();return false}
  async function startup({requested=false}={}){if(requested)return requestEntry();const state=await probe();if(state?.active&&rememberedEvent(state.event.id)){const next=await load();if(next?.active)return enterMode({remember:false,focus:false})}return state}
  function enterMode({remember=true,focus=true}={}){if(!payload?.active)return false;if(remember)rememberEvent(payload.event.id,true);modeActive=true;activeView='program';closeEntry({restore:false});openSection('live',{liveConfirmed:true});setLiveMode(true);render();if(focus)requestAnimationFrame(()=>root()?.querySelector('[data-live-tab="program"]')?.focus({preventScroll:true}));return true}
  function hasUnsavedJudge(){return judgeDrafts.size>0||[...judgeFiles.values()].some(items=>items.length)}
  function confirmLeaveJudge(){return !hasUnsavedJudge()||confirm('Máš rozepsané hodnocení. Opravdu ho chceš opustit bez uložení?')}
  function exitMode({navigate=true,section='overview',clearChoice=true}={}){if(modeActive&&!confirmLeaveJudge())return false;stopPolling();releaseMedia();closeQr();toggleMore(false);if(clearChoice&&payload?.event?.id)rememberEvent(payload.event.id,false);modeActive=false;setLiveMode(false);if(navigate)openSection(section);return true}
  async function poll(){pollTimer=0;if(!isOpen()||document.hidden||!navigator.onLine||!payload?.active)return;try{const next=await apiRequest('/api/live/state');pollFailures=0;if(!next.active||next.event?.id!==payload.event.id){await load();return}const signature=JSON.stringify(next.states||{});if(signature!==lastStateSignature){await load();return}payload.states=next.states;payload.now=next.now;void renderProgram();updateConnection(false)}catch{pollFailures+=1;updateConnection(true)}schedulePolling()}
  function schedulePolling(){clearTimeout(pollTimer);if(isOpen()&&!document.hidden&&navigator.onLine&&payload?.active)pollTimer=setTimeout(poll,Math.min(15000,2500*(2**Math.min(pollFailures,3))))}
  function stopPolling(){clearTimeout(pollTimer);pollTimer=0}
  async function submitVote(form){const button=form.querySelector('button[type=submit]'),value=Number(form.elements.score.value);if(!value)return toast('Vyber hodnocení 1 až 10.');setButtonBusy(button,true,'Ukládám…');try{await apiRequest(`/api/live/votes/${encodeURIComponent(form.dataset.liveVote)}`,{method:'PUT',body:{score:value}});await load();toast('Hlas je uložený. Do uzavření ho můžeš změnit.')}catch(error){toast(error.message||'Hlas se nepodařilo uložit.')}finally{setButtonBusy(button,false)}}
  function judgeValues(form){return{scores:Object.fromEntries(Object.keys(criteria).map(key=>[key,form.elements[key].value?Number(form.elements[key].value):null])),note:form.elements.note.value}}
  const liveError=(error,fallback)=>({own_car_score:'Vlastní auto nemůžeš hodnotit.',judge_forbidden:'Porotcovské hodnocení je dostupné jen oprávněné porotě.',judging_closed:'Porotcovské hodnocení je uzavřené.',incomplete_score:'Vyber známku 1–10 u všech kritérií.',invalid_score:'Zkontroluj zadané známky.'}[error?.payload?.error]||fallback);
  async function submitJudge(form,submitted){const buttons=form.querySelectorAll('button[type=submit]'),values=judgeValues(form),entryId=form.dataset.liveJudge,errorNode=form.querySelector('[data-live-judge-error]');if(submitted&&Object.values(values.scores).some(value=>!value))return toast('Vyber známku 1–10 u všech kritérií.');buttons.forEach(button=>button.disabled=true);if(errorNode)errorNode.textContent='';try{await apiRequest(`/api/live/judge/scores/${encodeURIComponent(entryId)}`,{method:'PUT',body:{...values,submitted}});const files=judgeFiles.get(entryId)||[];let failures=0;for(const item of files){item.status='uploading';item.error='';renderJudgePreviews(form,entryId);try{const data=new FormData();data.append('file',item.file);await apiRequestForm(`/api/live/judge/entries/${encodeURIComponent(entryId)}/photos`,data);item.status='uploaded'}catch(error){item.status='error';item.error=liveError(error,'Odeslání fotografie selhalo · zkus znovu');failures++}renderJudgePreviews(form,entryId)}for(let index=files.length-1;index>=0;index--)if(files[index].status==='uploaded'){releaseSelection(files[index]);files.splice(index,1)}if(!files.length)judgeFiles.delete(entryId);if(failures){if(errorNode)errorNode.textContent='Hodnocení je uložené, ale některé fotografie se neodeslaly. Zkus je odeslat znovu.';toast('Některé fotografie se nepodařilo odeslat.');return}judgeDrafts.delete(entryId);await load();toast(submitted?'Hodnocení je uložené.':'Koncept hodnocení je uložený.')}catch(error){const message=liveError(error,'Porotcovské hodnocení se nepodařilo uložit.');if(errorNode)errorNode.textContent=message;toast(message)}finally{buttons.forEach(button=>button.disabled=false)}}
  async function submitPhotos(form){const pending=galleryFiles.filter(item=>item.status!=='uploaded'),button=form.querySelector('button[type=submit]'),state=$('[data-live-upload-state]');if(!pending.length)return toast('Nejdřív vyber fotografie.');setButtonBusy(button,true,'Odesílám…');let sent=0,failed=0;for(const item of pending){item.status='uploading';item.error='';renderGalleryPreviews();try{const data=new FormData();data.append('file',item.file);data.append('caption',form.elements.caption.value);await apiRequestForm('/api/live/photos',data);item.status='uploaded';sent++}catch(error){item.status='error';item.error='Odeslání selhalo · zkus znovu';failed++}renderGalleryPreviews()}for(let index=galleryFiles.length-1;index>=0;index--)if(galleryFiles[index].status==='uploaded'){releaseSelection(galleryFiles[index]);galleryFiles.splice(index,1)}renderGalleryPreviews();if(!galleryFiles.length){form.elements.photos.value='';form.elements.caption.value=''}if(state)state.textContent=failed?`Odesláno ${sent}. ${failed} fotek zůstává připravených k opakování.`:`Odesláno ${sent} fotek ke schválení.`;if(sent){toast('Fotky čekají na schválení United týmem.');await load()}else toast('Nahrávání se nepodařilo dokončit.');setButtonBusy(button,false)}
  function selectScore(button,selector){const form=button.closest('form');if(!form)return;const name=button.dataset.liveJudgeCriterion||'score';if(form.elements[name])form.elements[name].value=button.dataset.liveScore||button.dataset.liveJudgeScore;form.querySelectorAll(selector).forEach(item=>{if((item.dataset.liveJudgeCriterion||'score')!==name)return;const selected=item===button;item.classList.toggle('is-selected',selected);item.setAttribute('aria-pressed',String(selected))})}
  function bind(){if(bound)return;bound=true;document.addEventListener('member:sectionchange',event=>{if(event.detail?.section==='live'&&modeActive)schedulePolling();else if(event.detail?.section!=='live')stopPolling()});document.addEventListener('visibilitychange',()=>document.hidden?stopPolling():schedulePolling());window.addEventListener('online',schedulePolling);window.addEventListener('offline',stopPolling);window.addEventListener('beforeunload',event=>{if(modeActive&&hasUnsavedJudge()){event.preventDefault();event.returnValue=''}});
    entryDialog()?.addEventListener('click',event=>{if(event.target.closest('[data-live-entry-cancel]')){closeEntry();return}if(event.target.closest('[data-live-entry-retry]')){void requestEntry({opener:entryOpener});return}if(event.target.closest('[data-live-entry-confirm]'))enterMode()});
    root()?.addEventListener('click',event=>{const removeGallery=event.target.closest('[data-live-remove-gallery-file]');if(removeGallery){const index=galleryFiles.findIndex(item=>item.id===removeGallery.dataset.liveRemoveGalleryFile);if(index>=0&&galleryFiles[index].status!=='uploading'){releaseSelection(galleryFiles[index]);galleryFiles.splice(index,1);renderGalleryPreviews()}return}const removeJudge=event.target.closest('[data-live-remove-judge-file]');if(removeJudge){const form=removeJudge.closest('[data-live-judge]'),entryId=form?.dataset.liveJudge,files=judgeFiles.get(entryId)||[],index=files.findIndex(item=>item.id===removeJudge.dataset.liveRemoveJudgeFile);if(index>=0&&files[index].status!=='uploading'){releaseSelection(files[index]);files.splice(index,1);if(!files.length)judgeFiles.delete(entryId);renderJudgePreviews(form,entryId)}return}const tabButton=event.target.closest('[data-live-tab],[data-live-tab-direct]');if(tabButton){setView(tabButton.dataset.liveTab||tabButton.dataset.liveTabDirect,{focus:true});return}if(event.target.closest('[data-live-more-toggle]')){toggleMore();return}if(event.target.closest('[data-live-exit]')){exitMode();return}if(event.target.closest('[data-live-retry]')){void load();return}if(event.target.closest('[data-live-open-qr]')){openQr(event.target.closest('button'));return}if(event.target.closest('[data-live-qr-close],[data-live-qr-backdrop]')){closeQr();return}if(event.target.closest('[data-live-open-votes]')){setView('showshine',{focus:true});requestAnimationFrame(()=>$('[data-live-vote-history]')?.scrollIntoView({block:'start'}));return}if(event.target.closest('[data-live-rate]')){setView('showshine',{focus:true});return}const judgeHistory=event.target.closest('[data-live-judge-history]');if(judgeHistory){judgeEntryId=judgeHistory.dataset.liveJudgeHistory;renderShowShine();return}const day=event.target.closest('[data-live-day]');if(day){programDay=day.dataset.liveDay;void renderProgram();return}const publicScore=event.target.closest('[data-live-score]');if(publicScore){selectScore(publicScore,'[data-live-score]');return}const judgeScore=event.target.closest('[data-live-judge-score]');if(judgeScore){selectScore(judgeScore,'[data-live-judge-score]');judgeDrafts.set(judgeScore.closest('form').dataset.liveJudge,judgeValues(judgeScore.closest('form')));return}});
    root()?.addEventListener('input',event=>{const form=event.target.closest('[data-live-judge]');if(form)judgeDrafts.set(form.dataset.liveJudge,judgeValues(form))});root()?.addEventListener('change',event=>{if(event.target.matches('[data-live-upload] input[name="photos"]')){addFiles(galleryFiles,event.target.files,8);event.target.value='';renderGalleryPreviews();return}const form=event.target.closest('[data-live-judge]');if(form&&event.target.name==='judgePhoto'){const entryId=form.dataset.liveJudge,files=judgeFiles.get(entryId)||[];addFiles(files,event.target.files,8);if(files.length)judgeFiles.set(entryId,files);event.target.value='';renderJudgePreviews(form,entryId)}});
    root()?.addEventListener('submit',event=>{const vote=event.target.closest('[data-live-vote]');if(vote){event.preventDefault();void submitVote(vote);return}const judge=event.target.closest('[data-live-judge]');if(judge){event.preventDefault();void submitJudge(judge,event.submitter?.hasAttribute('data-judge-submit'));return}const upload=event.target.closest('[data-live-upload]');if(upload){event.preventDefault();void submitPhotos(upload)}});
    document.addEventListener('click',event=>{if(!event.target.closest('[data-live-more-toggle],[data-live-more-menu]'))toggleMore(false)});document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(!qrDialog()?.hidden){event.preventDefault();closeQr();return}if(!entryDialog()?.hidden){event.preventDefault();closeEntry();return}if(!$('[data-live-more-menu]')?.hidden){event.preventDefault();toggleMore(false)}})}
  function reset(){closeEntry({restore:false});if(payload?.event?.id)rememberEvent(payload.event.id,false);judgeDrafts.clear();judgeEntryId='';stopPolling();releaseMedia();closeQr();modeActive=false;setLiveMode(false);payload=null;liveStatus=null;requestState='idle';lastStateSignature='';activeView='program';navState()}
  return{bind,load,probe,render,requestEntry,startup,reset};
}
