import qrcode from '../../vendor/qrcode-generator.mjs';
import { $, $$, esc, setButtonBusy, toast } from '../ui.js?v=20260902-phase3';

const labels={show_shine:'Show & Shine',best_exhaust:'Nejlepší výfuk'};
const stateLabels={idle:'Čeká na spuštění',live:'Hlasování běží',paused:'Hlasování pozastaveno',closed:'Hlasování uzavřeno',published:'Výsledky zveřejněny'};
const sessionKey='e36United.memberLiveMode.v1';

export function createMemberLive({apiBaseUrl,apiRequest,apiRequestForm,apiRequestBlob,openSection,setLiveMode}){
  let payload=null,liveStatus=null,requestState='idle',activeView='now',programDay='',judgeEntryId='',pollTimer=0,pollFailures=0,lastStateSignature='',bound=false,modeActive=false,entryOpener=null,mediaGeneration=0;
  const objectUrls=new Map(),judgeDrafts=new Map();
  const root=()=>document.querySelector('[data-member-live-mode]');
  const entryDialog=()=>document.querySelector('[data-member-live-entry]');
  const isOpen=()=>modeActive&&!root()?.hidden;
  const currency=value=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(value||0));
  const rememberedEvent=()=>{try{return sessionStorage.getItem(sessionKey)||''}catch{return''}};
  function rememberEvent(value){try{value?sessionStorage.setItem(sessionKey,value):sessionStorage.removeItem(sessionKey)}catch{}}
  function releaseMedia(){mediaGeneration+=1;root()?.querySelectorAll('img[src^="blob:"]').forEach(image=>image.remove());for(const url of objectUrls.values())URL.revokeObjectURL(url);objectUrls.clear()}
  async function imageFor(entry){if(!entry?.imageUrl)return '';if(objectUrls.has(entry.id))return objectUrls.get(entry.id);const generation=mediaGeneration;try{const blob=await apiRequestBlob(entry.imageUrl),url=URL.createObjectURL(blob);if(generation!==mediaGeneration||!modeActive){URL.revokeObjectURL(url);return ''}objectUrls.set(entry.id,url);return url}catch{return ''}}
  async function privateImageFor(path,key){if(objectUrls.has(key))return objectUrls.get(key);const generation=mediaGeneration;try{const blob=await apiRequestBlob(path),url=URL.createObjectURL(blob);if(generation!==mediaGeneration||!modeActive){URL.revokeObjectURL(url);return ''}objectUrls.set(key,url);return url}catch{return ''}}

  function navState(){
    const event=liveStatus&&liveStatus!==false?liveStatus:null,active=!!event,copy=document.querySelector('[data-live-nav-copy]');
    const copyText=active?`United ${event.year} · aktivní`:requestState==='error'?'Stav nedostupný':liveStatus===false?'Nyní neaktivní':'Načítám stav…';
    $$('[data-member-section="live"],[data-main-member-section="live"]').forEach(button=>{button.classList.toggle('is-live',active);button.classList.toggle('is-disabled',liveStatus===false);button.classList.toggle('is-error',requestState==='error');button.title=active?'Spustit aktuální UNITED LIVE':liveStatus===false?'UNITED LIVE teď není aktivní':'Ověřit dostupnost UNITED LIVE'});
    if(copy)copy.textContent=copyText;
  }
  function showEntry(opener=document.activeElement){entryOpener=opener;const dialog=entryDialog();if(!dialog)return;dialog.hidden=false;requestAnimationFrame(()=>dialog.querySelector('[data-live-entry-confirm]:not([hidden]),[data-live-entry-retry]:not([hidden]),[data-live-entry-cancel]')?.focus())}
  function closeEntry({restore=true}={}){const dialog=entryDialog();if(dialog)dialog.hidden=true;if(restore)entryOpener?.focus?.({preventScroll:true});entryOpener=null}
  function renderEntry(){
    const dialog=entryDialog();if(!dialog||dialog.hidden)return;
    const title=$('[data-live-entry-title]',dialog),copy=$('[data-live-entry-copy]',dialog),state=$('[data-live-entry-state]',dialog),confirm=$('[data-live-entry-confirm]',dialog),retry=$('[data-live-entry-retry]',dialog);
    if(requestState==='loading'||requestState==='idle'){
      title.textContent='Spustit UNITED LIVE?';copy.textContent='Přepneš se do režimu pro sraz. Zpět do portálu se můžeš kdykoliv vrátit.';state.textContent='Ověřuji potvrzený stav na serveru…';confirm.hidden=true;retry.hidden=true;
    }else if(requestState==='active'){
      title.textContent='Spustit UNITED LIVE?';copy.textContent='Přepneš se do režimu pro sraz. Zpět do portálu se můžeš kdykoliv vrátit.';state.textContent=`United ${payload.event.year} je aktivní${payload.event.venue?` · ${payload.event.venue}`:''}.`;confirm.hidden=false;retry.hidden=true;
    }else if(requestState==='inactive'){
      title.textContent='UNITED LIVE teď není aktivní.';copy.textContent='Běžný členský portál zůstává dostupný. LIVE zapne United tým pro konkrétní ročník.';state.textContent='Server nepotvrdil žádný aktivní LIVE ročník.';confirm.hidden=true;retry.hidden=true;
    }else{
      title.textContent='Stav UNITED LIVE se nepodařilo načíst.';copy.textContent='Není potvrzené, zda je LIVE aktivní. Zkus znovu načíst serverový stav.';state.textContent='Spojení nebo autorizovaný požadavek selhal.';confirm.hidden=true;retry.hidden=false;
    }
  }

  function setView(view){activeView=['now','program','rating','photos'].includes(view)?view:'now';$$('[data-live-view]').forEach(node=>{const active=node.dataset.liveView===activeView;node.hidden=!active;node.classList.toggle('is-active',active)});$$('[data-live-tab]').forEach(button=>button.classList.toggle('is-active',button.dataset.liveTab===activeView));if(activeView==='photos')renderGallery()}
  function activeDiscipline(){return Object.values(payload?.states||{}).find(item=>['live','paused'].includes(item.status)&&item.entry)||null}
  function nextProgram(){return payload?.now?.current||payload?.now?.next||null}
  function currentVote(entryId){return payload?.votes?.find(item=>item.entryId===entryId)?.score||null}
  function qrMarkup(){let svg='';try{if(payload?.me?.qrPayload){const qr=qrcode(0,'M');qr.addData(payload.me.qrPayload,'Byte');qr.make();svg=qr.createSvgTag({cellSize:4,margin:10,scalable:true})}}catch{}return svg}
  function participationMarkup(){
    const reservation=payload?.me?.reservation,qr=qrMarkup();
    return `<details class="live-card live-participation"><summary><span><small>MOJE ÚČAST &amp; POBYT</small><strong>${reservation?esc(reservation.accommodation):'Bez registrace'}</strong></span><b>Detail + QR</b></summary><div class="live-participation-detail">${reservation?`<dl><div><dt>Stav</dt><dd>${esc(reservation.status)}</dd></div><div><dt>Příjezd</dt><dd>${esc(reservation.arrival||'—')}</dd></div><div><dt>Posádka</dt><dd>${reservation.crew}</dd></div><div><dt>Ubytování</dt><dd>${esc(reservation.accommodation)}</dd></div><div><dt>Auto</dt><dd>${esc(reservation.car||'Neuvedeno')}</dd></div><div><dt>Platba</dt><dd>${currency(reservation.payment.paid)} / ${currency(reservation.payment.due)}</dd></div></dl>`:'<p>Program a schválené fotografie můžeš používat i bez registrace.</p>'}${qr?`<div class="member-live-qr"><span class="live-eyebrow">MŮJ QR</span>${qr}</div>`:'<p>QR identita zatím není vystavená. Organizátor tě může vyhledat ručně.</p>'}<button class="member-secondary" data-live-open-reservation type="button">Otevřít registraci</button></div></details>`;
  }
  function heroMarkup(current){
    if(current?.entry){const entry=current.entry;return `<article class="live-card live-card--hero" data-live-current-card>${entry.imageUrl?'<span data-live-current-image></span>':''}<div><span class="live-eyebrow">${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</span><h1>${esc(entry.car.nickname||entry.car.model)}</h1><p>${esc(entry.car.model)}${entry.car.body?' · '+esc(entry.car.body):''} · ${esc(entry.member.name)}</p>${current.status==='live'?'<button class="live-primary" data-live-rate type="button">Hodnotit auto ★</button>':'<p>Hodnocení je dočasně pozastavené.</p>'}</div></article>`}
    const item=nextProgram();return `<article class="live-card live-card--hero"><div><span class="live-eyebrow">${item?'PROGRAM · '+(payload.now.current?'PRÁVĚ TEĎ':'NÁSLEDUJE'):'UNITED LIVE'}</span><h1>${esc(item?.title||'Na místě s United.')}</h1><p>${item?`${esc(item.startsAt.slice(11,16))}${item.venue?' · '+esc(item.venue):''}`:'Aktuální program se objeví hned po zveřejnění.'}</p>${item?'<button class="live-primary" data-live-open-program type="button">Otevřít program</button>':''}</div></article>`;
  }
  async function renderNow(){const target=$('[data-live-now]');if(!target||!payload?.active)return;const current=activeDiscipline(),item=payload.now?.next;
    target.innerHTML=`<div class="live-now-grid">${heroMarkup(current)}<aside class="live-now-side">${item?`<article class="live-card live-next"><span class="live-eyebrow">NÁSLEDUJE</span><time>${esc(item.startsAt.slice(11,16))}</time><h2>${esc(item.title)}</h2><p>${esc(item.venue||'Místo bude upřesněno')}</p></article>`:''}${participationMarkup()}<div class="live-context-actions"><button data-live-tab-direct="photos" type="button">＋ Přidat fotku</button><button data-live-tab-direct="rating" type="button">★ Moje hlasy</button></div></aside></div>`;
    if(current?.entry?.imageUrl){const slot=target.querySelector('[data-live-current-image]'),url=await imageFor(current.entry);if(slot?.isConnected&&url)slot.outerHTML=`<img alt="${esc(current.entry.car.model)}" src="${url}">`}
  }
  function renderProgram(){const target=$('[data-live-program]');if(!target||!payload?.active)return;const days=[...new Set(payload.program.map(item=>item.day))];if(!days.includes(programDay))programDay=days[0]||'';target.innerHTML=days.length?`<nav class="live-program-days" aria-label="Dny programu">${days.map(day=>`<button class="${day===programDay?'is-active':''}" data-live-day="${esc(day)}" type="button">${new Date(day+'T12:00:00').toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'numeric'})}</button>`).join('')}</nav><div class="live-program-list">${payload.program.filter(item=>item.day===programDay).map(item=>`<article class="live-program-item ${payload.now?.current?.id===item.id?'is-current':payload.now?.next?.id===item.id?'is-next':''} ${item.status==='cancelled'?'is-cancelled':''}"><time>${esc(item.startsAt.slice(11,16))}${item.endsAt?'–'+esc(item.endsAt.slice(11,16)):''}</time><div><strong>${esc(item.title)}</strong><p>${[item.venue,item.description].filter(Boolean).map(esc).join(' · ')}</p></div>${item.status!=='scheduled'?`<em>${item.status==='cancelled'?'ZRUŠENO':'ZMĚNA'}</em>`:''}</article>`).join('')}</div>`:'<div class="live-empty">Program zatím není zveřejněný.</div>'}
  function disciplineSummary(){return `<section class="live-discipline-summary" aria-label="Stav disciplín">${['show_shine','best_exhaust'].map(discipline=>{const state=payload?.states?.[discipline]||{status:'idle'};return `<article><span>${esc(labels[discipline])}</span><strong>${esc(stateLabels[state.status]||state.status)}</strong><small>${state.entry?esc(state.entry.car.nickname||state.entry.car.model):'Bez prezentovaného auta'}</small></article>`}).join('')}</section>`}
  function ratingCard(current){if(!current?.entry)return '<div class="live-empty">Až moderátor představí auto v některé disciplíně, hodnocení se otevře tady.</div>';const own=current.entry.memberId===payload.me?.memberId,eligible=payload.me?.eligible&&!own,currentScore=currentVote(current.entry.id);return `<article class="live-card live-rating-card"><span class="live-eyebrow">${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</span><h3>${esc(current.entry.car.nickname||current.entry.car.model)}</h3><p>${esc(current.entry.member.name)} · ${esc(current.entry.car.model)}</p>${eligible&&current.status==='live'?`<form data-live-vote="${esc(current.entry.id)}"><p>Celkový dojem · vyber 1–10</p><div class="live-score">${Array.from({length:10},(_,i)=>`<button aria-pressed="${currentScore===i+1}" class="${currentScore===i+1?'is-selected':''}" data-live-score="${i+1}" type="button">${i+1}</button>`).join('')}</div><input name="score" type="hidden" value="${currentScore||''}"><button class="live-primary" type="submit">${currentScore?'Upravit hlas':'Uložit hlas'}</button></form>`:`<div class="live-empty">${own?'Vlastní auto hodnotit nemůžeš.':!payload.me?.reservation?'Hlas vyžaduje schválenou účast a check-in.':!payload.me?.present?'Po potvrzení přítomnosti organizátorem můžeš hlasovat.':'Hlasování teď nepřijímá hlasy.'}</div>`}${payload.me?.judge&&current.discipline==='show_shine'&&!own?judgeForm(current.entry):''}</article>`}
  function judgeForm(entry){const saved=payload?.judgeHistory?.find(item=>item.entryId===entry.id)||{},draft=judgeDrafts.get(entry.id)||{},scores={...(saved.scores||{}),...(draft.scores||{})},note=draft.note??saved.note??'',names={overall:'Celkový dojem',condition:'Stav a zpracování',cohesion:'Sladění a dotaženost',originality:'Originalita a nápad'};return `<form class="live-judge-form" data-live-judge="${esc(entry.id)}"><span class="live-eyebrow">POROTCOVSKÝ REŽIM · ${saved.submitted?'ODEVZDÁNO':'ROZEPSANÉ'}</span><h4>${esc(entry.car?.nickname||entry.car?.model||'Podrobné hodnocení')}</h4>${Object.entries(names).map(([key,label])=>`<label class="live-judge-row"><span>${label}</span><select name="${key}" required><option value="">—</option>${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${Number(scores[key])===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label>`).join('')}<textarea name="note" maxlength="1000" rows="3" placeholder="Interní poznámka poroty (volitelné)">${esc(note)}</textarea><label><span>Interní fotografie auta</span><input accept="image/jpeg,image/png,image/webp" capture="environment" name="judgePhoto" type="file"></label>${saved.photos?.length?`<div class="live-judge-photos">${saved.photos.map(photo=>`<span data-live-judge-photo="${esc(photo.imageUrl)}" data-live-judge-photo-key="judge-${esc(photo.id)}">Načítám foto…</span>`).join('')}</div>`:''}<div><button class="member-secondary" data-judge-draft type="submit">Uložit rozepsané</button> <button class="live-primary" data-judge-submit type="submit">Odevzdat hodnocení</button></div></form>`}
  async function hydrateJudgePhotos(target){for(const slot of target.querySelectorAll('[data-live-judge-photo]')){const url=await privateImageFor(slot.dataset.liveJudgePhoto,slot.dataset.liveJudgePhotoKey);if(slot.isConnected&&url)slot.outerHTML=`<img alt="Interní dokumentační fotografie auta" src="${url}">`}}
  function judgeHistoryMarkup(current){if(!payload.me?.judge)return '';const rows=payload.judgeHistory||[],selected=rows.find(item=>item.entryId===judgeEntryId),currentId=current?.entry?.id;return `<section class="live-history"><span class="live-eyebrow">MOJE POROTCOVSKÁ HODNOCENÍ</span>${rows.length?rows.map(item=>`<article><span>${esc(item.car.nickname||item.car.model)} · ${esc(item.member.name)}<small>${item.submitted?'Odevzdáno':'Rozepsáno'} · ${item.photos.length} foto</small></span>${item.memberId===payload.me.memberId?'<strong>Vlastní auto</strong>':`<button data-live-judge-history="${esc(item.entryId)}" type="button">Upravit</button>`}</article>`).join(''):'<p>Zatím není prezentované auto pro porotu.</p>'}</section>${selected&&selected.entryId!==currentId&&selected.memberId!==payload.me.memberId?judgeForm({id:selected.entryId,car:selected.car,member:selected.member}):''}`}
  function resultRows(items,type,discipline){const sorted=type==='jury'?[...items].sort((a,b)=>(a.juryRank??999)-(b.juryRank??999)):items;return sorted.map(item=>{const jury=type==='jury',value=jury?item.jury?.average:item.average,count=jury?item.jury?.judges:item.votes,rank=jury?item.juryRank:item.publicRank;return `<article><span>${rank?`${rank}. `:''}${esc(item.nickname||item.model)} · ${esc(item.memberNickname||item.name)}<small>${esc(labels[discipline])} · ${jury?'porota':'publikum'}</small></span><strong>${value==null?'Nehodnoceno':`${value} · ${count} ${jury?'porotců':'hlasů'}`}</strong></article>`}).join('')}
  function resultsMarkup(){const groups=payload?.results||{};if(!Object.keys(groups).length)return '';return `<section class="live-history"><span class="live-eyebrow">ZVEŘEJNĚNÉ VÝSLEDKY</span>${Object.entries(groups).map(([discipline,items])=>resultRows(items,'public',discipline)+(discipline==='show_shine'?resultRows(items,'jury',discipline):'')).join('')}</section>`}
  function renderRating(){const target=$('[data-live-rating]');if(!target||!payload?.active)return;const current=activeDiscipline();target.innerHTML=disciplineSummary()+ratingCard(current)+`<section class="live-history"><span class="live-eyebrow">MOJE HLASOVÁNÍ</span>${payload.votes?.length?payload.votes.map(item=>`<article><span>${esc(labels[item.discipline])} · ${esc(item.nickname||item.model)} · ${esc(item.memberNickname||item.name)}</span><strong>${item.score}/10</strong></article>`).join(''):'<p>Zatím nemáš uložený hlas.</p>'}</section>${judgeHistoryMarkup(current)}${resultsMarkup()}`;void hydrateJudgePhotos(target)}
  function renderGallery(){const target=$('[data-live-gallery]');if(!target)return;const status={pending:'Čeká na schválení',approved:'Schváleno',rejected:'Nevybráno do galerie'};const own=payload?.ownUploads?.length?`<section class="member-live-uploads"><span class="live-eyebrow">MOJE NAHRANÉ FOTKY</span>${payload.ownUploads.map(item=>`<p><span>${esc(item.caption||'Fotografie bez popisku')}</span><b data-status="${esc(item.status)}">${esc(status[item.status]||item.status)}</b></p>`).join('')}</section>`:'';const gallery=payload?.gallery?.length?payload.gallery.map(item=>`<figure><img alt="${esc(item.caption||'Fotografie z United')}" loading="lazy" src="${esc(apiBaseUrl+item.imageUrl)}"><figcaption>${esc(item.caption||'United LIVE')}</figcaption></figure>`).join(''):'<div class="live-empty">Schválené fotografie tohoto ročníku se objeví tady.</div>';target.innerHTML=own+`<div class="member-live-gallery-grid">${gallery}</div>`}

  function render(){const copy=$('[data-live-event-copy]'),app=$('[data-live-app]'),error=$('[data-live-error]'),state=$('[data-live-mode-state]');if(copy)copy.textContent=payload?.active?`United ${payload.event.year} · ${payload.event.venue||'právě probíhá'}`:requestState==='error'?'Stav se nepodařilo načíst':'LIVE není aktivní';if(state){state.textContent=payload?.active?'LIVE ACTIVE':requestState==='error'?'CHYBA':'LIVE OFF';state.classList.toggle('is-active',!!payload?.active)}if(error)error.hidden=requestState!=='error';if(app)app.hidden=!payload?.active||!modeActive;navState();renderEntry();if(!payload?.active||!modeActive){stopPolling();return}renderNow();renderProgram();renderRating();renderGallery();setView(activeView);schedulePolling()}
  async function load(){requestState='loading';renderEntry();try{const next=await apiRequest('/api/live');payload=next;liveStatus=next.active?next.event:false;requestState=next.active?'active':'inactive';pollFailures=0;lastStateSignature=JSON.stringify(next.states||{});if(!next.active&&modeActive){exitMode({navigate:true,clearSession:true});toast('UNITED LIVE byl ukončen. Vracíme tě do portálu.')}render();return next}catch(error){requestState='error';console.warn('UNITED LIVE unavailable',error);const connection=$('[data-live-connection]');if(connection){connection.textContent='LIVE je dočasně nedostupné';connection.classList.add('is-offline')}render();return null}}
  async function probe(){try{const state=await apiRequest('/api/live/state');liveStatus=state.active?state.event:false;requestState=state.active?'active':'inactive';navState();return state}catch(error){requestState='error';console.warn('UNITED LIVE state unavailable',error);navState();return null}}
  async function requestEntry({opener=document.activeElement}={}){showEntry(opener);requestState='loading';renderEntry();const next=await load();if(!next?.active)return false;if(rememberedEvent()===next.event.id){enterMode();return true}renderEntry();return false}
  async function startup({requested=false}={}){if(requested)return requestEntry();return probe()}
  function enterMode(){if(!payload?.active)return false;rememberEvent(payload.event.id);modeActive=true;closeEntry({restore:false});openSection('live',{liveConfirmed:true});setLiveMode(true);render();root()?.querySelector('[data-live-exit]')?.focus({preventScroll:true});return true}
  function exitMode({navigate=true,section='overview',clearSession=false}={}){stopPolling();releaseMedia();modeActive=false;setLiveMode(false);if(clearSession)rememberEvent('');if(navigate)openSection(section);return true}
  async function poll(){pollTimer=0;if(!isOpen()||document.hidden||!navigator.onLine||!payload?.active)return;try{const next=await apiRequest('/api/live/state');pollFailures=0;if(!next.active||next.event?.id!==payload.event.id){await load();return}const signature=JSON.stringify(next.states||{});if(signature!==lastStateSignature){await load();return}payload.states=next.states;payload.now=next.now;renderNow();renderProgram();const connection=$('[data-live-connection]');if(connection){connection.textContent='ONLINE · živý stav';connection.classList.remove('is-offline')}}catch{pollFailures+=1;const connection=$('[data-live-connection]');if(connection){connection.textContent='Spojení kolísá · zobrazuji poslední potvrzený stav';connection.classList.add('is-offline')}}schedulePolling()}
  function schedulePolling(){clearTimeout(pollTimer);if(isOpen()&&!document.hidden&&navigator.onLine&&payload?.active)pollTimer=setTimeout(poll,Math.min(15000,2500*(2**Math.min(pollFailures,3))))}
  function stopPolling(){clearTimeout(pollTimer);pollTimer=0}
  async function submitVote(form){const button=form.querySelector('button[type=submit]'),value=Number(form.elements.score.value);if(!value)return toast('Vyber hodnocení 1 až 10.');setButtonBusy(button,true,'Ukládám…');try{await apiRequest(`/api/live/votes/${encodeURIComponent(form.dataset.liveVote)}`,{method:'PUT',body:{score:value}});await load();toast('Hlas je uložený. Do uzavření ho můžeš změnit.')}catch(error){toast(error.message||'Hlas se nepodařilo uložit.')}finally{setButtonBusy(button,false)}}
  async function submitJudge(form,submitted){const buttons=form.querySelectorAll('button[type=submit]');buttons.forEach(button=>button.disabled=true);try{const scores=Object.fromEntries(['overall','condition','cohesion','originality'].map(key=>[key,form.elements[key].value?Number(form.elements[key].value):null]));await apiRequest(`/api/live/judge/scores/${encodeURIComponent(form.dataset.liveJudge)}`,{method:'PUT',body:{scores,note:form.elements.note.value,submitted}});const file=form.elements.judgePhoto.files?.[0];if(file){const data=new FormData();data.append('file',file);await apiRequestForm(`/api/live/judge/entries/${encodeURIComponent(form.dataset.liveJudge)}/photos`,data)}judgeDrafts.delete(form.dataset.liveJudge);await load();toast(submitted?'Hodnocení bylo odevzdané.':'Rozepsané hodnocení je uložené.')}catch(error){toast(error.message||'Porotcovské hodnocení se nepodařilo uložit.')}finally{buttons.forEach(button=>button.disabled=false)}}
  async function submitPhotos(form){const files=[...form.elements.photos.files||[]].slice(0,8),button=form.querySelector('button[type=submit]'),state=$('[data-live-upload-state]');if(!files.length)return;setButtonBusy(button,true,'Odesílám…');let sent=0;try{for(const file of files){const data=new FormData();data.append('file',file);data.append('caption',form.elements.caption.value);await apiRequestForm('/api/live/photos',data);sent+=1}form.reset();if(state)state.textContent=`Odesláno ${sent} fotek ke schválení.`;toast('Fotky čekají na schválení United týmem.');await load()}catch(error){if(state)state.textContent=`Odesláno ${sent} z ${files.length}. Zbytek můžeš zkusit znovu.`;toast(error.message||'Nahrávání se nepodařilo dokončit.')}finally{setButtonBusy(button,false)}}
  function bind(){if(bound)return;bound=true;document.addEventListener('member:sectionchange',event=>{if(event.detail?.section==='live'&&modeActive)schedulePolling();else if(event.detail?.section!=='live')stopPolling()});document.addEventListener('visibilitychange',()=>document.hidden?stopPolling():schedulePolling());window.addEventListener('online',schedulePolling);window.addEventListener('offline',stopPolling);
    entryDialog()?.addEventListener('click',event=>{if(event.target.closest('[data-live-entry-cancel]')){closeEntry();return}if(event.target.closest('[data-live-entry-retry]')){void requestEntry({opener:entryOpener});return}if(event.target.closest('[data-live-entry-confirm]'))enterMode()});
    root()?.addEventListener('click',event=>{const tabButton=event.target.closest('[data-live-tab],[data-live-tab-direct]');if(tabButton){setView(tabButton.dataset.liveTab||tabButton.dataset.liveTabDirect);return}if(event.target.closest('[data-live-exit]')){exitMode();return}if(event.target.closest('[data-live-retry]')){void load();return}if(event.target.closest('[data-live-open-program]')){setView('program');return}if(event.target.closest('[data-live-rate]')){setView('rating');return}const judgeHistory=event.target.closest('[data-live-judge-history]');if(judgeHistory){judgeEntryId=judgeHistory.dataset.liveJudgeHistory;renderRating();return}const day=event.target.closest('[data-live-day]');if(day){programDay=day.dataset.liveDay;renderProgram();return}const scoreButton=event.target.closest('[data-live-score]');if(scoreButton){const form=scoreButton.closest('form');form.elements.score.value=scoreButton.dataset.liveScore;form.querySelectorAll('[data-live-score]').forEach(button=>{const selected=button===scoreButton;button.classList.toggle('is-selected',selected);button.setAttribute('aria-pressed',String(selected))});return}if(event.target.closest('[data-live-open-reservation]'))exitMode({section:'reservation'})});
    root()?.addEventListener('input',event=>{const form=event.target.closest('[data-live-judge]');if(!form)return;judgeDrafts.set(form.dataset.liveJudge,{scores:Object.fromEntries(['overall','condition','cohesion','originality'].map(key=>[key,form.elements[key].value?Number(form.elements[key].value):null])),note:form.elements.note.value})});
    root()?.addEventListener('submit',event=>{const vote=event.target.closest('[data-live-vote]');if(vote){event.preventDefault();void submitVote(vote);return}const judge=event.target.closest('[data-live-judge]');if(judge){event.preventDefault();void submitJudge(judge,event.submitter?.hasAttribute('data-judge-submit'));return}const upload=event.target.closest('[data-live-upload]');if(upload){event.preventDefault();void submitPhotos(upload)}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!entryDialog()?.hidden){event.preventDefault();closeEntry()}})}
  function reset(){closeEntry({restore:false});exitMode({navigate:false,clearSession:true});judgeDrafts.clear();judgeEntryId='';payload=null;liveStatus=null;requestState='idle';lastStateSignature='';navState()}
  return{bind,load,probe,render,requestEntry,startup,reset};
}
