import qrcode from '../../vendor/qrcode-generator.mjs';
import { $, $$, esc, setButtonBusy, toast } from '../ui.js?v=20260902-phase3';

const labels={show_shine:'Show & Shine',best_exhaust:'Nejlepší výfuk'};
const stateLabels={idle:'Čeká na spuštění',live:'Hlasování běží',paused:'Hlasování pozastaveno',closed:'Hlasování uzavřeno',published:'Výsledky zveřejněny'};

export function createMemberLive({apiBaseUrl,apiRequest,apiRequestForm,apiRequestBlob,openSection}){
  let payload=null,liveStatus=null,activeView='now',programDay='',judgeEntryId='',pollTimer=0,pollFailures=0,lastStateSignature='',bound=false;
  const objectUrls=new Map();
  const judgeDrafts=new Map();
  const panel=()=>document.querySelector('[data-member-panel="live"]');
  const isOpen=()=>panel()?.classList.contains('is-active')&&!panel()?.hidden;
  const currency=value=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number(value||0));
  function releaseMedia(){for(const url of objectUrls.values())URL.revokeObjectURL(url);objectUrls.clear()}
  async function imageFor(entry){if(!entry?.imageUrl)return '';if(objectUrls.has(entry.id))return objectUrls.get(entry.id);try{const blob=await apiRequestBlob(entry.imageUrl),url=URL.createObjectURL(blob);objectUrls.set(entry.id,url);return url}catch{return ''}}
  async function privateImageFor(path,key){if(objectUrls.has(key))return objectUrls.get(key);try{const blob=await apiRequestBlob(path),url=URL.createObjectURL(blob);objectUrls.set(key,url);return url}catch{return ''}}
  function navState(){const event=payload?.active?payload.event:liveStatus&&liveStatus!==false?liveStatus:null,active=!!event,disabled=liveStatus===false||payload?.active===false,copy=document.querySelector('[data-live-nav-copy]');$$('[data-member-section="live"],[data-main-member-section="live"]').forEach(button=>{button.classList.toggle('is-live',active);button.classList.toggle('is-disabled',disabled);button.title=active?'Otevřít aktuální UNITED LIVE':'Otevřít informace o UNITED LIVE'});if(copy)copy.textContent=active?`United ${event.year} · právě teď`:'Mimo provoz'}

  function setView(view){activeView=['now','program','rating','photos'].includes(view)?view:'now';$$('[data-live-view]').forEach(node=>{const active=node.dataset.liveView===activeView;node.hidden=!active;node.classList.toggle('is-active',active)});$$('[data-live-tab]').forEach(button=>button.classList.toggle('is-active',button.dataset.liveTab===activeView));if(activeView==='photos')renderGallery()}
  function activeDiscipline(){return Object.values(payload?.states||{}).find(item=>['live','paused'].includes(item.status)&&item.entry)||null}
  function nextProgram(){return payload?.now?.current||payload?.now?.next||null}
  function currentVote(entryId){return payload?.votes?.find(item=>item.entryId===entryId)?.score||null}
  function heroMarkup(current){
    if(current?.entry){const entry=current.entry;return `<article class="live-card live-card--hero" data-live-current-card>${entry.imageUrl?'<span data-live-current-image></span>':''}<div><span class="live-eyebrow">${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</span><h3>${esc(entry.car.nickname||entry.car.model)}</h3><p>${esc(entry.car.model)}${entry.car.body?' · '+esc(entry.car.body):''} · ${esc(entry.member.name)}</p>${current.status==='live'?'<button class="live-primary" data-live-rate type="button">Hodnotit auto ★</button>':'<p>Hodnocení je dočasně pozastavené.</p>'}</div></article>`}
    const item=nextProgram();return `<article class="live-card live-card--hero"><div><span class="live-eyebrow">${item?'PROGRAM · '+(payload.now.current?'PRÁVĚ TEĎ':'NÁSLEDUJE'):'UNITED LIVE'}</span><h3>${esc(item?.title||'Na místě s United.')}</h3><p>${item?`${esc(item.startsAt.slice(11,16))}${item.venue?' · '+esc(item.venue):''}`:'Aktuální program se objeví hned po zveřejnění.'}</p>${item?'<button class="live-primary" data-live-open-program type="button">Otevřít program</button>':''}</div></article>`;
  }
  async function renderNow(){const root=$('[data-live-now]');if(!root||!payload?.active)return;const current=activeDiscipline(),item=payload.now?.next;
    root.innerHTML=`<div class="live-now-grid">${heroMarkup(current)}<div><div class="live-quick-grid"><button data-live-quick="qr" type="button"><span>▦</span><b>Můj QR</b></button><button data-live-quick="stay" type="button"><span>⌂</span><b>Můj pobyt</b></button><button data-live-tab-direct="photos" type="button"><span>＋</span><b>Přidat fotku</b></button><button data-live-tab-direct="rating" type="button"><span>★</span><b>Moje hlasy</b></button></div>${item?`<article class="live-card live-next"><span class="live-eyebrow">NÁSLEDUJE</span><time>${esc(item.startsAt.slice(11,16))}</time><h4>${esc(item.title)}</h4><p>${esc(item.venue||'Místo bude upřesněno')}</p></article>`:''}</div></div>`;
    if(current?.entry?.imageUrl){const slot=root.querySelector('[data-live-current-image]'),url=await imageFor(current.entry);if(slot&&url)slot.outerHTML=`<img alt="${esc(current.entry.car.model)}" src="${url}">`}
  }
  function renderProgram(){const root=$('[data-live-program]');if(!root||!payload?.active)return;const days=[...new Set(payload.program.map(item=>item.day))];if(!days.includes(programDay))programDay=days[0]||'';root.innerHTML=days.length?`<nav class="live-program-days" aria-label="Dny programu">${days.map(day=>`<button class="${day===programDay?'is-active':''}" data-live-day="${esc(day)}" type="button">${new Date(day+'T12:00:00').toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'numeric'})}</button>`).join('')}</nav><div class="live-program-list">${payload.program.filter(item=>item.day===programDay).map(item=>`<article class="live-program-item ${payload.now?.current?.id===item.id?'is-current':payload.now?.next?.id===item.id?'is-next':''} ${item.status==='cancelled'?'is-cancelled':''}"><time>${esc(item.startsAt.slice(11,16))}${item.endsAt?'–'+esc(item.endsAt.slice(11,16)):''}</time><div><strong>${esc(item.title)}</strong><p>${[item.venue,item.description].filter(Boolean).map(esc).join(' · ')}</p></div>${item.status!=='scheduled'?`<em>${item.status==='cancelled'?'ZRUŠENO':'ZMĚNA'}</em>`:''}</article>`).join('')}</div>`:'<div class="live-empty">Program zatím není zveřejněný.</div>'}
  function ratingCard(current){
    if(!current?.entry)return '<div class="live-empty">Až moderátor představí auto, hodnocení se otevře tady.</div>';
    const own=current.entry.memberId===payload.me?.memberId,eligible=payload.me?.eligible&&!own,currentScore=currentVote(current.entry.id);
    return `<article class="live-card live-rating-card"><span class="live-eyebrow">${esc(labels[current.discipline])} · ${esc(stateLabels[current.status])}</span><h3>${esc(current.entry.car.nickname||current.entry.car.model)}</h3><p>${esc(current.entry.member.name)} · ${esc(current.entry.car.model)}</p>${eligible&&current.status==='live'?`<form data-live-vote="${esc(current.entry.id)}"><p>Celkový dojem · vyber 1–10</p><div class="live-score">${Array.from({length:10},(_,i)=>`<button aria-pressed="${currentScore===i+1}" class="${currentScore===i+1?'is-selected':''}" data-live-score="${i+1}" type="button">${i+1}</button>`).join('')}</div><input name="score" type="hidden" value="${currentScore||''}"><button class="live-primary" type="submit">${currentScore?'Upravit hlas':'Uložit hlas'}</button></form>`:`<div class="live-empty">${own?'Vlastní auto hodnotit nemůžeš.':!payload.me?.reservation?'Hlasování je dostupné i s programem, ale hlas vyžaduje schválenou účast a check-in.':!payload.me?.present?'Po potvrzení přítomnosti organizátorem můžeš hlasovat.':'Hlasování teď nepřijímá hlasy.'}</div>`}${payload.me?.judge&&current.discipline==='show_shine'&&!own?judgeForm(current.entry):''}</article>`;
  }
  function judgeForm(entry){const saved=payload?.judgeHistory?.find(item=>item.entryId===entry.id)||{},draft=judgeDrafts.get(entry.id)||{},scores={...(saved.scores||{}),...(draft.scores||{})},note=draft.note??saved.note??'',names={overall:'Celkový dojem',condition:'Stav a zpracování',cohesion:'Sladění a dotaženost',originality:'Originalita a nápad'};return `<form class="live-judge-form" data-live-judge="${esc(entry.id)}"><span class="live-eyebrow">POROTCOVSKÝ REŽIM · ${saved.submitted?'ODEVZDÁNO':'ROZEPSANÉ'}</span><h4>${esc(entry.car?.nickname||entry.car?.model||'Podrobné hodnocení')}</h4>${Object.entries(names).map(([key,label])=>`<label class="live-judge-row"><span>${label}</span><select name="${key}" required><option value="">—</option>${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${Number(scores[key])===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label>`).join('')}<textarea name="note" maxlength="1000" rows="3" placeholder="Interní poznámka poroty (volitelné)">${esc(note)}</textarea><label><span>Interní fotografie auta</span><input accept="image/jpeg,image/png,image/webp" capture="environment" name="judgePhoto" type="file"></label>${saved.photos?.length?`<div class="live-judge-photos">${saved.photos.map(photo=>`<span data-live-judge-photo="${esc(photo.imageUrl)}" data-live-judge-photo-key="judge-${esc(photo.id)}">Načítám foto…</span>`).join('')}</div>`:''}<div><button class="member-secondary" data-judge-draft type="submit">Uložit rozepsané</button> <button class="live-primary" data-judge-submit type="submit">Odevzdat hodnocení</button></div></form>`}
  async function hydrateJudgePhotos(root){for(const slot of root.querySelectorAll('[data-live-judge-photo]')){const url=await privateImageFor(slot.dataset.liveJudgePhoto,slot.dataset.liveJudgePhotoKey);if(slot.isConnected&&url)slot.outerHTML=`<img alt="Interní dokumentační fotografie auta" src="${url}">`}}
  function judgeHistoryMarkup(current){if(!payload.me?.judge)return '';const rows=payload.judgeHistory||[],selected=rows.find(item=>item.entryId===judgeEntryId),currentId=current?.entry?.id;return `<section class="live-history"><span class="live-eyebrow">MOJE POROTCOVSKÁ HODNOCENÍ</span>${rows.length?rows.map(item=>`<article><span>${esc(item.car.nickname||item.car.model)} · ${esc(item.member.name)}<small>${item.submitted?'Odevzdáno':'Rozepsáno'} · ${item.photos.length} foto</small></span>${item.memberId===payload.me.memberId?'<strong>Vlastní auto</strong>':`<button data-live-judge-history="${esc(item.entryId)}" type="button">Upravit</button>`}</article>`).join(''):'<p>Zatím není prezentované auto pro porotu.</p>'}</section>${selected&&selected.entryId!==currentId&&selected.memberId!==payload.me.memberId?judgeForm({id:selected.entryId,car:selected.car,member:selected.member}):''}`}
  function renderRating(){const root=$('[data-live-rating]');if(!root||!payload?.active)return;const current=activeDiscipline();root.innerHTML=ratingCard(current)+`<section class="live-history"><span class="live-eyebrow">MOJE HLASOVÁNÍ</span>${payload.votes?.length?payload.votes.map(item=>`<article><span>${esc(labels[item.discipline])} · ${esc(item.nickname||item.model)} · ${esc(item.memberNickname||item.name)}</span><strong>${item.score}/10</strong></article>`).join(''):'<p>Zatím nemáš uložený hlas.</p>'}</section>${judgeHistoryMarkup(current)}${resultsMarkup()}`;void hydrateJudgePhotos(root)}
  function resultRows(items,type,discipline){const sorted=type==='jury'?[...items].sort((a,b)=>(a.juryRank??999)-(b.juryRank??999)):items;return sorted.map(item=>{const jury=type==='jury',value=jury?item.jury?.average:item.average,count=jury?item.jury?.judges:item.votes,rank=jury?item.juryRank:item.publicRank;return `<article><span>${rank?`${rank}. `:''}${esc(item.nickname||item.model)} · ${esc(item.memberNickname||item.name)}<small>${esc(labels[discipline])} · ${jury?'porota':'publikum'}</small></span><strong>${value==null?'Nehodnoceno':`${value} · ${count} ${jury?'porotců':'hlasů'}`}</strong></article>`}).join('')}
  function resultsMarkup(){const groups=payload?.results||{};if(!Object.keys(groups).length)return '';return `<section class="live-history"><span class="live-eyebrow">ZVEŘEJNĚNÉ VÝSLEDKY</span>${Object.entries(groups).map(([discipline,items])=>resultRows(items,'public',discipline)+(discipline==='show_shine'?resultRows(items,'jury',discipline):'')).join('')}</section>`}
  function renderGallery(){const root=$('[data-live-gallery]');if(!root)return;const status={pending:'Čeká na schválení',approved:'Schváleno',rejected:'Nevybráno do galerie'};const own=payload?.ownUploads?.length?`<section class="member-live-uploads"><span class="live-eyebrow">MOJE NAHRANÉ FOTKY</span>${payload.ownUploads.map(item=>`<p><span>${esc(item.caption||'Fotografie bez popisku')}</span><b data-status="${esc(item.status)}">${esc(status[item.status]||item.status)}</b></p>`).join('')}</section>`:'';const gallery=payload?.gallery?.length?payload.gallery.map(item=>`<figure><img alt="${esc(item.caption||'Fotografie z United')}" loading="lazy" src="${esc(apiBaseUrl+item.imageUrl)}"><figcaption>${esc(item.caption||'United LIVE')}</figcaption></figure>`).join(''):'<div class="live-empty">Schválené fotografie tohoto ročníku se objeví tady.</div>';root.innerHTML=own+`<div class="member-live-gallery-grid">${gallery}</div>`}
  function renderSheet(kind){const sheet=$('[data-live-sheet]'),content=$('[data-live-sheet-content]');if(!sheet||!content)return;if(kind==='qr'){let svg='';try{if(payload.me?.qrPayload){const qr=qrcode(0,'M');qr.addData(payload.me.qrPayload,'Byte');qr.make();svg=qr.createSvgTag({cellSize:5,margin:12,scalable:true})}}catch{}content.innerHTML=`<div class="member-live-qr"><span class="live-eyebrow">MŮJ QR</span><h3>Identifikace účastníka</h3>${svg||'<p>QR identita zatím není vystavená. Organizátor tě může vyhledat ručně.</p>'}</div>`}else{const r=payload.me?.reservation;content.innerHTML=`<span class="live-eyebrow">MŮJ POBYT · UNITED ${esc(payload.event.year)}</span><h3>${r?'Tvoje účast':'Bez registrace'}</h3>${r?`<dl><div><dt>Stav</dt><dd>${esc(r.status)}</dd></div><div><dt>Příjezd</dt><dd>${esc(r.arrival||'—')}</dd></div><div><dt>Posádka</dt><dd>${r.crew}</dd></div><div><dt>Ubytování</dt><dd>${esc(r.accommodation)}</dd></div><div><dt>Auto</dt><dd>${esc(r.car||'Neuvedeno')}</dd></div><div><dt>Platba</dt><dd>${currency(r.payment.paid)} / ${currency(r.payment.due)}</dd></div></dl><button class="member-secondary" data-live-open-reservation type="button">Otevřít registraci</button>`:'<p>Program a schválené fotografie můžeš používat i bez registrace.</p>'}`};sheet.hidden=false;sheet.querySelector('button')?.focus()}
  function render(){const copy=$('[data-live-event-copy]'),disabled=$('[data-live-disabled]'),app=$('[data-live-app]');if(copy)copy.textContent=payload?.active?`United ${payload.event.year} · ${payload.event.venue||'právě probíhá'}`:'LIVE není aktivní pro žádný ročník.';if(disabled)disabled.hidden=!!payload?.active;if(app)app.hidden=!payload?.active;navState();if(!payload?.active){stopPolling();return}renderNow();renderProgram();renderRating();renderGallery();setView(activeView);schedulePolling()}
  async function load(){try{payload=await apiRequest('/api/live');liveStatus=payload.active?payload.event:false;pollFailures=0;lastStateSignature=JSON.stringify(payload.states||{});render()}catch(error){console.warn('UNITED LIVE unavailable',error);const connection=$('[data-live-connection]');if(connection){connection.textContent='LIVE je dočasně nedostupné';connection.classList.add('is-offline')}}}
  async function probe(){try{const state=await apiRequest('/api/live/state');liveStatus=state.active?state.event:false;navState()}catch(error){console.warn('UNITED LIVE state unavailable',error)}}
  async function poll(){pollTimer=0;if(!isOpen()||document.hidden||!navigator.onLine||!payload?.active)return;try{const next=await apiRequest('/api/live/state'),signature=JSON.stringify(next.states||{});pollFailures=0;if(signature!==lastStateSignature){await load();return}payload.states=next.states;payload.now=next.now;renderNow();renderProgram();const connection=$('[data-live-connection]');if(connection){connection.textContent='ONLINE · živý stav';connection.classList.remove('is-offline')}}catch{pollFailures+=1;const connection=$('[data-live-connection]');if(connection){connection.textContent='Spojení kolísá · zobrazuji poslední potvrzený stav';connection.classList.add('is-offline')}}schedulePolling()}
  function schedulePolling(){clearTimeout(pollTimer);if(isOpen()&&!document.hidden&&navigator.onLine&&payload?.active)pollTimer=setTimeout(poll,Math.min(15000,2500*(2**Math.min(pollFailures,3))))}
  function stopPolling(){clearTimeout(pollTimer);pollTimer=0}
  async function submitVote(form){const button=form.querySelector('button[type=submit]'),value=Number(form.elements.score.value);if(!value)return toast('Vyber hodnocení 1 až 10.');setButtonBusy(button,true,'Ukládám…');try{await apiRequest(`/api/live/votes/${encodeURIComponent(form.dataset.liveVote)}`,{method:'PUT',body:{score:value}});await load();toast('Hlas je uložený. Do uzavření ho můžeš změnit.')}catch(error){toast(error.message||'Hlas se nepodařilo uložit.')}finally{setButtonBusy(button,false)}}
  async function submitJudge(form,submitted){const buttons=form.querySelectorAll('button[type=submit]');buttons.forEach(button=>button.disabled=true);try{const scores=Object.fromEntries(['overall','condition','cohesion','originality'].map(key=>[key,form.elements[key].value?Number(form.elements[key].value):null]));await apiRequest(`/api/live/judge/scores/${encodeURIComponent(form.dataset.liveJudge)}`,{method:'PUT',body:{scores,note:form.elements.note.value,submitted}});const file=form.elements.judgePhoto.files?.[0];if(file){const data=new FormData();data.append('file',file);await apiRequestForm(`/api/live/judge/entries/${encodeURIComponent(form.dataset.liveJudge)}/photos`,data)}judgeDrafts.delete(form.dataset.liveJudge);await load();toast(submitted?'Hodnocení bylo odevzdané.':'Rozepsané hodnocení je uložené.')}catch(error){toast(error.message||'Porotcovské hodnocení se nepodařilo uložit.')}finally{buttons.forEach(button=>button.disabled=false)}}
  function bind(){if(bound)return;bound=true;document.addEventListener('member:sectionchange',event=>{if(event.detail?.section==='live')load();else stopPolling()});document.addEventListener('visibilitychange',()=>document.hidden?stopPolling():schedulePolling());window.addEventListener('online',schedulePolling);window.addEventListener('offline',stopPolling);
    panel()?.addEventListener('click',event=>{const tab=event.target.closest('[data-live-tab],[data-live-tab-direct]');if(tab){setView(tab.dataset.liveTab||tab.dataset.liveTabDirect);return}const quick=event.target.closest('[data-live-quick]');if(quick){renderSheet(quick.dataset.liveQuick);return}if(event.target.closest('[data-live-sheet-close]')){$('[data-live-sheet]').hidden=true;return}if(event.target.closest('[data-live-exit]')){openSection('overview');return}if(event.target.closest('[data-live-open-program]')){setView('program');return}if(event.target.closest('[data-live-rate]')){setView('rating');return}const judgeHistory=event.target.closest('[data-live-judge-history]');if(judgeHistory){judgeEntryId=judgeHistory.dataset.liveJudgeHistory;renderRating();return}const day=event.target.closest('[data-live-day]');if(day){programDay=day.dataset.liveDay;renderProgram();return}const scoreButton=event.target.closest('[data-live-score]');if(scoreButton){const form=scoreButton.closest('form');form.elements.score.value=scoreButton.dataset.liveScore;form.querySelectorAll('[data-live-score]').forEach(button=>{const selected=button===scoreButton;button.classList.toggle('is-selected',selected);button.setAttribute('aria-pressed',String(selected))});return}if(event.target.closest('[data-live-open-reservation]')){$('[data-live-sheet]').hidden=true;openSection('reservation')}});
    panel()?.addEventListener('input',event=>{const form=event.target.closest('[data-live-judge]');if(!form)return;judgeDrafts.set(form.dataset.liveJudge,{scores:Object.fromEntries(['overall','condition','cohesion','originality'].map(key=>[key,form.elements[key].value?Number(form.elements[key].value):null])),note:form.elements.note.value})});
    panel()?.addEventListener('submit',event=>{const vote=event.target.closest('[data-live-vote]');if(vote){event.preventDefault();submitVote(vote);return}const judge=event.target.closest('[data-live-judge]');if(judge){event.preventDefault();submitJudge(judge,event.submitter?.hasAttribute('data-judge-submit'));return}});
    $('[data-live-upload]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,files=[...form.elements.photos.files||[]].slice(0,8),button=form.querySelector('button[type=submit]'),state=$('[data-live-upload-state]');if(!files.length)return;setButtonBusy(button,true,'Odesílám…');let sent=0;try{for(const file of files){const data=new FormData();data.append('file',file);data.append('caption',form.elements.caption.value);await apiRequestForm('/api/live/photos',data);sent+=1}form.reset();if(state)state.textContent=`Odesláno ${sent} fotek ke schválení.`;toast('Fotky čekají na schválení United týmem.');await load()}catch(error){if(state)state.textContent=`Odesláno ${sent} z ${files.length}. Zbytek můžeš zkusit znovu.`;toast(error.message||'Nahrávání se nepodařilo dokončit.')}finally{setButtonBusy(button,false)}})}
  function reset(){stopPolling();releaseMedia();judgeDrafts.clear();judgeEntryId='';payload=null;liveStatus=null;lastStateSignature='';navState()}
  return{bind,load,probe,render,reset};
}
