import {esc,date,statusLabel,orderMarkup,bindOrder,addressFields,readAddress} from '../../merch/order-view.js?v=20260924-merch2';
import {money,imageSource} from '../../merch/catalog.js?v=20260924-merch2';
export function createMemberMerch({request,getUser}){
 let generation=0,loadedFor=null,orders=[],page=1,filter='active';
 const panel=document.querySelector('[data-member-panel="merch"]'),list=panel.querySelector('[data-merch-orders]'),detail=panel.querySelector('[data-merch-detail]');
 panel.classList.add('merch-connected');document.querySelector('[data-merch-address]').classList.add('merch-connected');
 async function load(){const user=getUser();if(!user)return;const g=++generation;list.textContent='Načítám objednávky…';try{const result=await request(`/api/merch/orders?filter=${filter}&page=${page}`);if(g!==generation||getUser()?.uid!==user.uid)return;orders=result.orders;loadedFor=user.uid;render();panel.querySelector('[data-merch-next]').disabled=!result.hasMore;}catch(error){if(g===generation)list.textContent=error.message;}}
 function render(){
  list.innerHTML=orders.length?orders.map(o=>`<button class="merch-order-card" type="button" data-merch-order="${o.id}"><img src="${esc(imageSource(o.snapshot.lines[0]))}" alt="" width="60" height="72"><span><strong>${esc(o.number)} · ${money(o.snapshot.totalMinor)}</strong><small>${statusLabel[o.state.status]} · ${statusLabel[o.payment.status]} · ${date(o.createdAt)}</small></span></button>`).join(''):'<p>V této části zatím nejsou žádné objednávky.</p>';
 }
 async function open(id){const user=getUser(),g=generation;try{const result=await request('/api/merch/orders/'+encodeURIComponent(id));if(g!==generation||getUser()?.uid!==user?.uid)return;show(result.order);}catch(error){detail.textContent=error.message;}}
 function show(order){detail.hidden=false;detail.innerHTML=orderMarkup(order);bindOrder(detail,order,{request,onChange:async updated=>{show(updated);await load();await summary();}});detail.scrollIntoView({block:'start',behavior:'instant'});}
 panel.addEventListener('click',e=>{const b=e.target.closest('[data-merch-order]');if(b)void open(b.dataset.merchOrder);});
 panel.querySelectorAll('[data-merch-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.merchFilter;page=1;void load();});
 panel.querySelector('[data-merch-next]').onclick=()=>{page++;void load();};panel.querySelector('[data-merch-prev]').onclick=()=>{page=Math.max(1,page-1);void load();};
 const overview=document.querySelector('[data-merch-overview]'),payments=document.querySelector('[data-merch-payments]');overview.classList.add('merch-connected');payments.classList.add('merch-connected');
 document.querySelectorAll('[data-member-payment-tab]').forEach(button=>button.onclick=()=>{const merch=button.dataset.memberPaymentTab==='merch';payments.hidden=!merch;document.querySelector('[data-payments-list]').hidden=merch;document.querySelectorAll('[data-member-payment-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(merch)void summary();});
 async function summary(){const user=getUser();if(!user)return;const g=generation;try{const result=await request('/api/merch/orders?filter=active');if(g!==generation||getUser()?.uid!==user.uid)return;const o=result.orders[0];overview.hidden=!o;if(o)overview.innerHTML=`<a class="merch-order-card" href="member.html?section=merch"><img src="${esc(imageSource(o.snapshot.lines[0]))}" alt=""><span><b>UNITED MERCH · ${result.orders.length}${result.hasMore?'+':''} aktivních</b><small>${esc(o.number)} · ${money(o.snapshot.totalMinor)} · ${statusLabel[o.payment.status]}</small></span></a>`;payments.innerHTML=result.orders.length?result.orders.map(o=>`<p><a href="member.html?section=merch">${esc(o.number)} · ${o.payment.remainingMinor?money(o.payment.remainingMinor)+' k úhradě':statusLabel[o.payment.status]}</a></p>`).join(''):'<p>Žádné aktivní platby za Merch.</p>';}catch{overview.hidden=true;payments.textContent='Merch platby nejsou nyní dostupné.';}}
 async function address(){const host=document.querySelector('[data-merch-address]'),user=getUser(),g=generation;if(!user)return;try{const result=await request('/api/merch/address');if(g!==generation||getUser()?.uid!==user.uid)return;host.innerHTML=`<h3>Výchozí dodací údaje</h3><form>${addressFields(result.address||{name:user.displayName,email:user.email})}<button class="shop-button" type="submit">Uložit dodací údaje</button><p role="status"></p></form>`;host.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await request('/api/merch/address',{method:'PUT',body:readAddress(e.currentTarget)});host.querySelector('[role=status]').textContent='Dodací údaje byly uloženy. Starší objednávky se nemění.';}catch(error){host.querySelector('[role=status]').textContent=error.message;}finally{b.disabled=false;}};}catch(error){host.textContent=error.message;}}
 window.addEventListener('member:sectionchange',e=>{if(e.detail.section==='merch'){void load();const id=new URL(location.href).searchParams.get('order');if(id)void open(id);}if(e.detail.section==='account')void address();if(['overview','payments'].includes(e.detail.section))void summary();});
 return {reset(){generation++;loadedFor=null;orders=[];list.replaceChildren();detail.replaceChildren();overview.replaceChildren();overview.hidden=true;payments.replaceChildren();document.querySelector('[data-merch-address]').replaceChildren();},startup(){void summary();}};
}
