import {esc,date,statusLabel,orderMarkup,bindOrder,addressFields,readAddress} from '../../merch/order-view.js?v=20260924-workspace1';
import {money,imageSource} from '../../merch/catalog.js?v=20260924-merch2';
import {renderMerchAddress} from './merch-address.js?v=20260924-workspace1';
export function createMemberMerch({request,getUser}){
 let generation=0,loadedFor=null,orders=[],page=1,filter='active',listScroll=0;
 const panel=document.querySelector('[data-member-panel="merch"]'),list=panel.querySelector('[data-merch-orders]'),detail=panel.querySelector('[data-merch-detail]');
 panel.classList.add('merch-connected');document.querySelector('[data-merch-address]').classList.add('merch-connected');
 async function load(){const user=getUser();if(!user)return;const g=++generation;list.textContent='Načítám objednávky…';try{const result=await request(`/api/merch/orders?filter=${filter}&page=${page}`);if(g!==generation||getUser()?.uid!==user.uid)return;orders=result.orders;loadedFor=user.uid;render();panel.querySelector('[data-merch-next]').disabled=!result.hasMore;panel.querySelector('[data-merch-prev]').disabled=page===1;panel.querySelector('[data-merch-pagination]').hidden=page===1&&!result.hasMore;}catch(error){if(g===generation)list.textContent=error.message;}}
 function render(){
  panel.querySelectorAll('[data-merch-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.merchFilter===filter)));
  list.innerHTML=orders.length?orders.map(o=>`<button class="merch-order-card" type="button" data-merch-order="${o.id}"><img src="${esc(imageSource(o.snapshot.lines[0]))}" alt="" width="60" height="72"><span><strong>${esc(o.number)} · ${money(o.snapshot.totalMinor)}</strong><small>${statusLabel[o.state.status]} · ${statusLabel[o.payment.status]} · ${date(o.createdAt)}</small><small>Otevřít objednávku →</small></span></button>`).join(''):'<article class="portal-empty-state"><span aria-hidden="true">♧</span><div><strong>Zatím tu nemáš žádné objednávky.</strong><p>Kolekci najdeš přes Prohlédnout nabídku.</p></div></article>';
 }
 async function open(id){const user=getUser(),g=generation;try{const result=await request('/api/merch/orders/'+encodeURIComponent(id));if(g!==generation||getUser()?.uid!==user?.uid)return;show(result.order);}catch(error){detail.textContent=error.message;}}
 function show(order){if(detail.hidden)listScroll=scrollY;detail.hidden=false;list.hidden=true;detail.innerHTML='<button class="member-secondary" type="button" data-merch-back>← Zpět k objednávkám</button>'+orderMarkup(order);detail.querySelector('[data-merch-back]').onclick=()=>{detail.hidden=true;list.hidden=false;scrollTo({top:listScroll,behavior:'instant'});list.querySelector(`[data-merch-order="${CSS.escape(order.id)}"]`)?.focus({preventScroll:true})};bindOrder(detail,order,{request,onChange:async updated=>{show(updated);await load();await summary();}});detail.scrollIntoView({block:'start',behavior:'instant'});}
 panel.addEventListener('click',e=>{const b=e.target.closest('[data-merch-order]');if(b)void open(b.dataset.merchOrder);});
 panel.querySelectorAll('[data-merch-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.merchFilter;page=1;detail.hidden=true;list.hidden=false;void load();});
 panel.querySelector('[data-merch-next]').onclick=()=>{page++;void load();};panel.querySelector('[data-merch-prev]').onclick=()=>{page=Math.max(1,page-1);void load();};
 const overview=document.querySelector('[data-merch-overview]'),payments=document.querySelector('[data-merch-payments]');overview.classList.add('merch-connected');payments.classList.add('merch-connected');
 function syncPaymentTab(){const merch=new URL(location.href).searchParams.get('payment')==='merch';payments.hidden=!merch;document.querySelector('[data-payments-list]').hidden=merch;document.querySelector('[data-member-panel="payments"] .member-section-head p').textContent=merch?'Přehled plateb za tvoje objednávky UNITED MERCH.':'Přehled plateb za tvoji účast na United.';document.querySelectorAll('[data-member-payment-tab]').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.memberPaymentTab==='merch')===merch)));if(merch)void summary();}
 document.querySelectorAll('[data-member-payment-tab]').forEach(button=>button.onclick=()=>{const url=new URL(location.href);url.searchParams.set('payment',button.dataset.memberPaymentTab);history.pushState(history.state,'',url);syncPaymentTab();});
 window.addEventListener('popstate',syncPaymentTab);
 window.addEventListener('member:sectionchange',event=>{if(event.detail.section==='payments')syncPaymentTab();});
 async function summary(){const user=getUser();if(!user)return;const g=generation;try{const result=await request('/api/merch/orders?filter=active');if(g!==generation||getUser()?.uid!==user.uid)return;const o=result.orders[0];overview.hidden=!o;if(o)overview.innerHTML=`<a class="merch-order-card" href="member.html?section=merch"><img src="${esc(imageSource(o.snapshot.lines[0]))}" alt=""><span><b>UNITED MERCH · ${result.orders.length}${result.hasMore?'+':''} aktivních</b><small>${esc(o.number)} · ${money(o.snapshot.totalMinor)} · ${statusLabel[o.payment.status]}</small></span></a>`;payments.innerHTML=result.orders.length?result.orders.map(o=>`<details class="portal-card" data-member-merch-payment="${esc(o.id)}"><summary>${esc(o.number)} · ${o.payment.remainingMinor?money(o.payment.remainingMinor)+' k úhradě':statusLabel[o.payment.status]}</summary>${orderMarkup(o,{paymentOnly:true})}<a class="shop-button" href="member.html?section=merch&order=${encodeURIComponent(o.id)}">Otevřít objednávku →</a></details>`).join(''):'<p>Žádné aktivní platby za Merch.</p>';for(const o of result.orders){const host=payments.querySelector(`[data-member-merch-payment="${CSS.escape(o.id)}"]`);if(host)bindOrder(host,o,{request});}}catch{overview.hidden=true;payments.textContent='Merch platby nejsou nyní dostupné.';}}
 async function address(){const host=document.querySelector('[data-merch-address]'),user=getUser(),g=generation;if(!user)return;const isCurrent=()=>g===generation&&getUser()?.uid===user.uid;try{const result=await request('/api/merch/address');if(isCurrent())renderMerchAddress(host,{address:result.address,user,request,isCurrent});}catch(error){if(isCurrent())host.textContent=error.message;}}
 window.addEventListener('member:sectionchange',e=>{if(e.detail.section==='merch'){void load();const id=new URL(location.href).searchParams.get('order');if(id)void open(id);}if(e.detail.section==='account')void address();if(['overview','payments'].includes(e.detail.section))void summary();});
 return {reset(){generation++;loadedFor=null;orders=[];page=1;filter='active';listScroll=0;list.replaceChildren();list.hidden=false;detail.replaceChildren();detail.hidden=true;overview.replaceChildren();overview.hidden=true;payments.replaceChildren();document.querySelector('[data-merch-address]').replaceChildren();},startup(){void summary();}};
}
