import {money,imageSource} from './catalog.js?v=20260924-merch2';
import {paymentQrSvg} from '../member/modules/planner/payments.js?v=20260924-merch2';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const statusLabel={new:'Nová',preparing:'Připravuje se',ready:'Připraveno k převzetí',sent:'Odesláno',completed:'Dokončeno',cancelled:'Zrušeno',expired:'Vypršela',unpaid:'Nezaplaceno',underpaid:'Nedoplatek',paid:'Zaplaceno',overpaid:'Přeplatek'};
export const date=value=>new Date(value).toLocaleString('cs-CZ');
export function addressFields(value={},prefix=''){
 return [['name','Jméno a příjmení','name'],['email','E-mail','email'],['phone','Telefon','tel'],['street','Ulice a číslo','street-address'],['city','Obec','address-level2'],['postalCode','PSČ','postal-code']].map(([k,label,auto])=>`<label>${label}<input name="${prefix+k}" value="${esc(value[k])}" autocomplete="${auto}" ${['name','email'].includes(k)?'required':''} type="${k==='email'?'email':'text'}" maxlength="180"></label>`).join('')+`<label>Země<input value="Česká republika" readonly></label><label>Poznámka k doručení<textarea name="${prefix}note" maxlength="1000" rows="2">${esc(value.note)}</textarea></label>`;
}
export const readAddress=form=>Object.fromEntries(['name','email','phone','street','city','postalCode','note'].map(k=>[k,new FormData(form).get(k)||'']).concat([['country','CZ']]));
export function linesMarkup(snapshot){return snapshot.lines.map(l=>`<article class="merch-order-line"><img src="${esc(imageSource(l))}" width="80" height="96" alt="${esc(l.name)}"><div><strong>${esc(l.name)}</strong><p>${esc(l.type)} · ${esc(l.color)} · ${esc(l.size)}</p><span>${l.quantity} × ${money(l.unitPriceMinor)}</span></div><b>${money(l.totalMinor)}</b></article>`).join('')+`<dl class="merch-totals"><div><dt>Sleva člena</dt><dd>−${money(snapshot.discountMinor)}</dd></div><div><dt>${snapshot.shipping==='pickup'?'Osobní převzetí':'Doprava na adresu'}</dt><dd>${money(snapshot.shippingMinor)}</dd></div><div><dt>Celkem</dt><dd><strong>${money(snapshot.totalMinor)}</strong></dd></div></dl>`;}
export function orderMarkup(order,{admin=false}={}){
 const s=order.snapshot,state=order.state,p=order.payment,a=state.deliveryAddress||s.address;
 const action=(kind,label)=>`<button type="button" class="shop-button" data-order-action="${kind}">${label}</button>`;
 return `<div class="merch-order" data-order-id="${order.id}"><header><span>UNITED MERCH</span><h3>${esc(order.number)}</h3><p>${statusLabel[state.status]} · ${statusLabel[p.status]}</p></header>${linesMarkup(s)}
 <details><summary>Kontakt a předání</summary><p>${esc(a.name)} · ${esc(a.email)}<br>${esc(a.phone)}<br>${s.shipping==='address'?esc(`${a.street}, ${a.postalCode} ${a.city}, ČR`):esc(s.pickupInstructions)}<br>${esc(a.note)}</p><p>${esc(s.deliveryInformation)}</p></details>
 ${p.reviewRequired?'<p class="shop-notice">Částečná úhrada po lhůtě: tým ji ručně dořeší.</p>':''}
 ${state.status==='expired'?'<p class="shop-notice">Lhůta uplynula. Pokud jsi již zaplatil, kontaktuj tým; evidenci plateb kontrolujeme ručně.</p>':''}
 <div class="merch-pay"><div><h4>${p.remainingMinor?`${['cancelled','expired'].includes(state.status)?'Neuhrazená částka':'K úhradě'} ${money(p.remainingMinor)}`:p.overpaidMinor?`Přeplatek ${money(p.overpaidMinor)}`:'Uhrazeno – děkujeme'}</h4><p>Evidováno ${money(p.paidMinor)}${p.refundedMinor?` · Vráceno ${money(p.refundedMinor)}`:''}</p>
 ${p.spayd?`<p>Zaplať do ${date(order.expiresAt)}.</p>${[['Účet',s.bank.accountDisplay],['VS',order.variableSymbol],['Částka',money(p.remainingMinor)]].map(([label,value])=>`<button type="button" class="shop-button" data-copy="${esc(value)}">${label}: ${esc(value)} ⧉</button>`).join('')}<small>Platbu kartou připravujeme.</small>`:''}</div>${p.spayd?`<div class="merch-qr">${paymentQrSvg(p.spayd)}</div>`:''}</div>
 ${state.tracking?.number?`<p>${esc(state.tracking.carrier)} · ${esc(state.tracking.number)} ${state.tracking.url?`<a href="${esc(state.tracking.url)}" target="_blank" rel="noopener noreferrer">Sledovat zásilku</a>`:''}</p>`:''}
 <div class="merch-actions">${!['cancelled','expired','sent','completed'].includes(state.status)?action('cancel',!admin&&p.paidMinor?'Požádat o zrušení':'Zrušit objednávku'):''}${action('withdraw','Odstoupit od smlouvy')}${action('complaint','Reklamovat')}<button type="button" class="shop-button" data-order-print>Tisk souhrnu</button></div>
 ${admin?`<section class="merch-admin-payment"><h4>Evidence plateb a vyřízení</h4><form data-order-admin-form><label>Operace<select name="action"><option value="payment">Přidat přijatou úhradu</option><option value="paid">Označit jako zaplaceno – doplnit jen zbývající částku</option><option value="refund">Evidovat ruční vrácení peněz</option><option value="status">Změna vyřízení</option><option value="restore">Obnovit vypršelou / zrušenou objednávku</option><option value="address">Opravit dodací údaje</option></select></label><label>Částka Kč<input name="amount" type="number" min="0.01" step="0.01"></label><label>Datum přijetí<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Stav<select name="status">${['preparing','ready','sent','completed'].map(k=>`<option value="${k}">${statusLabel[k]}</option>`).join('')}</select></label><label>Dopravce<input name="carrier"></label><label>Číslo zásilky<input name="trackingNumber"></label><label>Sledovací odkaz HTTPS<input name="trackingUrl" type="url"></label><label>Důvod / poznámka<textarea name="reason" maxlength="1000"></textarea></label><label><input type="checkbox" name="deliveryConfirmed">Možnost dodání jsem znovu ověřil</label><details><summary>Oprava adresy</summary>${addressFields(a)}</details><button class="shop-button shop-primary" type="submit">Uložit operaci</button></form>
 <h4>Jednotlivé úhrady</h4>${state.payments.map(x=>`<p>${money(x.amountMinor)} · ${esc(x.date)} ${x.voided?'Opravený záznam (nepočítá se)':`<button type="button" class="shop-button" data-void-payment="${x.id}">Opravit chybný záznam</button>`}</p>`).join('')}
 <button class="shop-button" data-order-label type="button">Adresní štítek / PDF</button><button class="shop-button" data-order-email-status type="button">Stav e-mailů</button><button class="shop-button" data-order-email-send type="button">Odeslat čekající e-maily</button></section>`:''}
 <details><summary>Historie a požadavky</summary>${state.requests.map(r=>`<p>${esc(r.kind)} · ${date(r.at)} · ${esc(r.text)} ${r.resolved?esc(r.resolved.text):admin?`<button type="button" class="shop-button" data-resolve-request="${r.id}">Vyřídit</button>`:'Čeká na tým'}</p>`).join('')}${state.history.map(h=>`<p>${date(h.at)} · ${esc(h.action)} ${esc(h.reason)}</p>`).join('')}</details><p role="status" data-order-message></p></div>`;
}
export function bindOrder(root,order,{request,admin=false,onChange=()=>{}}){
 let busy=false;const path=`/api/${admin?'admin/':''}merch/orders/${order.id}`;
 const message=value=>root.querySelector('[data-order-message]').textContent=value;
 async function change(input){if(busy)return;busy=true;const operationKey=crypto.randomUUID();root.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await request(path,{method:'PATCH',body:{...input,revision:order.revision,operationKey}});onChange(result.order);}catch(e){message(e.message);root.querySelectorAll('button').forEach(b=>b.disabled=false);}finally{busy=false;}}
 root.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);message('Zkopírováno.');}catch{message(`Zkopíruj ručně: ${b.dataset.copy}`);}});
 root.querySelectorAll('[data-order-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.orderAction;const reason=action==='cancel'?(admin?'Zrušení administrátorem':'Zrušení členem'):prompt(action==='withdraw'?'Potvrď odstoupení. Můžeš doplnit zprávu:':'Popiš vadu / reklamaci:');if(reason===null)return;if(confirm(action==='withdraw'?'Potvrdit odstoupení od smlouvy?':'Potvrdit tento požadavek?'))change({action,reason});});
 root.querySelector('[data-order-admin-form]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);change({...Object.fromEntries(f),amountMinor:Math.round(Number(f.get('amount'))*100),deliveryConfirmed:f.has('deliveryConfirmed'),address:readAddress(e.currentTarget)});});
 root.querySelectorAll('[data-void-payment]').forEach(b=>b.onclick=()=>{const reason=prompt('Důvod opravy chybné úhrady:');if(reason)change({action:'void-payment',paymentId:b.dataset.voidPayment,reason});});
 root.querySelectorAll('[data-resolve-request]').forEach(b=>b.onclick=()=>{const reason=prompt('Výsledek vyřízení:');if(reason)change({action:'resolve-request',requestId:b.dataset.resolveRequest,reason});});
 root.querySelector('[data-order-email-status]')?.addEventListener('click',async()=>{try{const result=await request(path+'/email');message(result.messages.map(m=>`${m.kind}: ${m.status} ${m.error_code||''}`).join(' · '));}catch(e){message(e.message);}});
 root.querySelector('[data-order-email-send]')?.addEventListener('click',async()=>{if(!confirm('Odeslat dosud neodeslané čekající e-maily této objednávky? Nejasné a chybové pokusy se neopakují.'))return;try{const result=await request(path+'/email',{method:'POST'});message(result.messages.map(m=>`${m.kind}: ${m.status}`).join(' · '));}catch(e){message(e.message);}});
 const documents=document.createElement('details');documents.innerHTML=`<summary>Podmínky přijaté ${date(order.createdAt)} · ${esc(order.snapshot.termsVersion)}</summary>${Object.values(order.snapshot.documents).map(text=>`<pre class="merch-document">${esc(text)}</pre>`).join('')}`;root.querySelector('[data-order-id]').append(documents);
 const adminForm=root.querySelector('[data-order-admin-form]');if(adminForm){const relevant={payment:['amount','date'],paid:['date'],refund:['amount','reason'],status:['status','carrier','trackingNumber','trackingUrl'],restore:['deliveryConfirmed','reason'],address:['name','email','phone','street','city','postalCode','note','reason']};const update=()=>{const fields=relevant[adminForm.elements.action.value]||[];for(const input of adminForm.querySelectorAll('input,textarea,select')){if(input.name==='action')continue;input.closest('label').hidden=!fields.includes(input.name);}adminForm.querySelector('details').hidden=adminForm.elements.action.value!=='address';};adminForm.elements.action.addEventListener('change',update);update();}
 function print(label=false){
  const win=window.open('','_blank');if(!win){message('Povol tiskové okno.');return;}
  const a=order.state.deliveryAddress||order.snapshot.address,s=order.snapshot.seller;
  win.onload=()=>win.print();win.document.write(`<!doctype html><html lang="cs"><meta charset="utf-8"><title>${esc(order.number)}</title><style>body{font:16px Arial;margin:25mm;color:#111}img{max-width:70px}article,dl div{display:flex;gap:20px;margin:12px 0}dt{min-width:180px}small{display:block}</style><body>${label?`<h2>Příjemce</h2><p>${esc(a.name)}<br>${esc(a.street)}<br>${esc(a.postalCode)} ${esc(a.city)}<br>Česká republika</p><h3>Odesílatel</h3><p>${esc(s.name)}<br>${esc(s.street)}<br>${esc(s.postalCode)} ${esc(s.city)}</p><p>${esc(order.number)}</p><small>Adresní štítek – není přepravním štítkem dopravce.</small>`:`<h1>${esc(order.number)}</h1>${linesMarkup(order.snapshot)}<p>${statusLabel[order.state.status]} · ${statusLabel[order.payment.status]}</p><p>Vytvořeno ${date(order.createdAt)}</p><h2>Kontakt a předání</h2><p>${esc(a.name)} · ${esc(a.email)}<br>${esc(a.phone)}<br>${order.snapshot.shipping==='address'?esc(`${a.street}, ${a.postalCode} ${a.city}, ČR`):esc(order.snapshot.pickupInstructions)}<br>${esc(a.note)}</p><p>${esc(order.snapshot.deliveryInformation)}</p><h2>Platba</h2><p>Účet ${esc(order.snapshot.bank.accountDisplay)} · VS ${esc(order.variableSymbol)}<br>Evidováno ${money(order.payment.paidMinor)} · Vráceno ${money(order.payment.refundedMinor)}<br>Rozdíl k ceně ${money(order.payment.remainingMinor)} · Přeplatek ${money(order.payment.overpaidMinor)}</p><p>Prodávající: ${esc(s.name)}, IČO ${esc(s.ico)}, ${esc(s.street)}, ${esc(s.postalCode)} ${esc(s.city)}</p>`}</body></html>`);win.document.close();
 }
 root.querySelector('[data-order-print]')?.addEventListener('click',()=>print());root.querySelector('[data-order-label]')?.addEventListener('click',()=>print(true));
}
