import { firebaseConfig, portalConfig } from './firebase-config.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const firebaseReady = firebaseConfig?.apiKey && !firebaseConfig.apiKey.startsWith('PASTE_') && firebaseConfig.projectId && !firebaseConfig.projectId.startsWith('PASTE_');
let firebase = null, currentUser = null;
const localKey='e36UnitedMemberPreviewV18';
const defaultData=()=>({
  profile:{name:'United Member',nickname:'Driver',email:'',phone:'',createdAt:new Date().toISOString()},
  history:portalConfig.unitedYears.map(y=>({year:y,attended:false,verified:false,winner:false,category:''})),
  cars:[], reservation:null, bonuses:[]
});
let data=loadLocal();
function loadLocal(){try{return {...defaultData(),...(JSON.parse(localStorage.getItem(localKey))||{})}}catch{return defaultData()}}
function saveLocal(){localStorage.setItem(localKey,JSON.stringify(data)); renderAll();}
function toast(msg){const el=$('[data-toast]'); el.textContent=msg; el.classList.add('is-visible'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('is-visible'),2600)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(){return Math.random().toString(36).slice(2,10)}

async function initFirebase(){
  if(!firebaseReady){setMode('LOCAL PREVIEW'); return;}
  try{
    const appMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js');
    const authMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js');
    const dbMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js');
    const app=appMod.initializeApp(firebaseConfig); const auth=authMod.getAuth(app); const db=dbMod.getFirestore(app);
    firebase={...authMod,...dbMod,auth,db}; setMode('FIREBASE LIVE');
    authMod.onAuthStateChanged(auth,async user=>{currentUser=user;if(user){await loadRemote();showApp()}else showAuth()});
  }catch(e){console.warn('Firebase unavailable, using preview mode',e);setMode('LOCAL PREVIEW');}
}
function setMode(t){$$('[data-mode-badge]').forEach(x=>x.textContent=t);const s=$('[data-sync-state]');if(s)s.textContent=t;$$('[data-demo-hint]').forEach(x=>x.hidden=t==='FIREBASE LIVE')}
async function loadRemote(){if(!firebase||!currentUser)return;const ref=firebase.doc(firebase.db,'members',currentUser.uid);const snap=await firebase.getDoc(ref);if(snap.exists())data={...defaultData(),...snap.data()};else{data=defaultData();data.profile.email=currentUser.email||'';}const carsSnap=await firebase.getDocs(firebase.collection(firebase.db,'members',currentUser.uid,'cars'));data.cars=carsSnap.docs.map(d=>({id:d.id,...d.data()}));if(!snap.exists())await syncRemote();renderAll()}
async function syncRemote(){if(firebase&&currentUser){const {cars,...memberData}=data;await firebase.setDoc(firebase.doc(firebase.db,'members',currentUser.uid),memberData,{merge:true});for(const car of cars){const {id,...carData}=car;await firebase.setDoc(firebase.doc(firebase.db,'members',currentUser.uid,'cars',id),carData,{merge:true});}}else localStorage.setItem(localKey,JSON.stringify(data));}
async function commit(msg='Uloženo'){await syncRemote();renderAll();toast(msg)}

function showAuth(){ $('[data-auth-view]').hidden=false; $('[data-app-view]').hidden=true; }
function showApp(){ $('[data-auth-view]').hidden=true; $('[data-app-view]').hidden=false; renderAll(); }

$$('[data-auth-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('is-active',x===btn));$$('[data-auth-form]').forEach(f=>f.classList.toggle('is-active',f.dataset.authForm===btn.dataset.authTab))}));
$$('[data-toggle-password]').forEach(b=>b.addEventListener('click',()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password'}));

$('[data-auth-form="login"]').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password');try{if(firebaseReady&&firebase){await firebase.signInWithEmailAndPassword(firebase.auth,email,password)}else{data.profile.email=email;saveLocal();showApp();toast('Preview profil otevřen')}}catch(err){toast(authError(err))}});
$('[data-auth-form="register"]').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password'),name=fd.get('name'),nickname=fd.get('nickname')||name.split(' ')[0];try{if(firebaseReady&&firebase){const cred=await firebase.createUserWithEmailAndPassword(firebase.auth,email,password);currentUser=cred.user;await firebase.updateProfile(currentUser,{displayName:name});data=defaultData();data.profile={...data.profile,name,nickname,email};await syncRemote();await firebase.sendEmailVerification(currentUser);showApp();toast('United ID vytvořeno · ověření e-mailu odesláno')}else{data=defaultData();data.profile={...data.profile,name,nickname,email};saveLocal();showApp();toast('United ID vytvořeno v preview režimu')}}catch(err){toast(authError(err))}});
$('[data-password-reset]').addEventListener('click',async()=>{const email=$('[data-auth-form="login"] input[name="email"]').value;if(!email)return toast('Nejdřív vyplň e-mail.');if(firebaseReady&&firebase){try{await firebase.sendPasswordResetEmail(firebase.auth,email);toast('Odkaz pro nové heslo byl odeslán.')}catch(e){toast(authError(e))}}else toast('Preview mode: reset hesla se neposílá.')});
$('[data-logout]').addEventListener('click',async()=>{if(firebase&&currentUser)await firebase.signOut(firebase.auth);currentUser=null;showAuth()});
function authError(e){const c=e?.code||'';if(c.includes('invalid-credential'))return 'E-mail nebo heslo nesedí.';if(c.includes('email-already'))return 'Tento e-mail už United ID má.';if(c.includes('weak-password'))return 'Heslo musí mít alespoň 6 znaků.';return 'Akci se nepodařilo dokončit.'}

$$('.member-nav-item[data-member-section]').forEach(b=>b.addEventListener('click',()=>openSection(b.dataset.memberSection)));
$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>openSection(b.dataset.jump)));
function openSection(id){$$('.member-nav-item[data-member-section]').forEach(b=>b.classList.toggle('is-active',b.dataset.memberSection===id));$$('[data-member-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.memberPanel===id));if(innerWidth<700)window.scrollTo({top:82,behavior:'smooth'})}

const badgeDefs=[
  {id:'first',icon:'1×',name:'First United',desc:'První účast',test:d=>attended(d)>=1},
  {id:'regular',icon:'3×',name:'United Regular',desc:'3 ověřené účasti',test:d=>verified(d)>=3},
  {id:'veteran',icon:'5×',name:'Veteran',desc:'5 ověřených účastí',test:d=>verified(d)>=5},
  {id:'og',icon:'OG',name:'Old School',desc:'Member since 2022 nebo dřív',test:d=>(memberSince(d)||9999)<=2022},
  {id:'winner',icon:'★',name:'S&S Winner',desc:'Ověřená výhra',test:d=>d.history.some(h=>h.verified&&h.winner)},
  {id:'garage',icon:'▦',name:'Full Garage',desc:'3 auta v garáži',test:d=>d.cars.length>=3},
  {id:'twelve',icon:'12',name:'Full Points',desc:'12 / 12 United Points',test:d=>points(d)>=12}
];
function attended(d=data){return d.history.filter(h=>h.attended).length} function verified(d=data){return d.history.filter(h=>h.attended&&h.verified).length}
function memberSince(d=data){const y=d.history.filter(h=>h.attended).map(h=>h.year);return y.length?Math.min(...y):null}
function points(d=data){const p=portalConfig.points;return Math.min(p.rewardThreshold,d.history.reduce((n,h)=>n+(h.attended&&h.verified?p.attendance:0)+(h.winner&&h.verified?p.showShineWin:0),0)+(d.bonuses||[]).reduce((n,b)=>n+(b.points||0),0))}
function lifetimePoints(d=data){const p=portalConfig.points;return d.history.reduce((n,h)=>n+(h.attended&&h.verified?p.attendance:0)+(h.winner&&h.verified?p.showShineWin:0),0)+(d.bonuses||[]).reduce((n,b)=>n+(b.points||0),0)}
function status(d=data){const n=verified(d);if(n>=5)return 'VETERAN';if(n>=3)return 'REGULAR';if(n>=1)return 'MEMBER';return 'ROOKIE'}

function renderAll(){renderProfile();renderPoints();renderBadges();renderGarage();renderHistory();renderReservation();renderRewards()}
function renderProfile(){const p=data.profile||{};const nick=p.nickname||p.name?.split(' ')[0]||'Driver';$('[data-member-nickname]').textContent=nick;$('[data-card-name]').textContent=(p.name||'United Member').toUpperCase();$('[data-card-id]').textContent=String((p.email||nick).split('').reduce((a,c)=>a+c.charCodeAt(0),0)%900+100);const car=data.cars.find(c=>c.primary)||data.cars[0];$('[data-card-car]').textContent=car?`${car.body} · ${car.model}${car.nickname?' · '+car.nickname:''}`:'BMW E36 · Garage pending';$('[data-member-since]').textContent=memberSince()||'—';$('[data-history-since]').textContent=memberSince()||'—';$('[data-attendance-count]').textContent=attended();$('[data-member-status]').textContent=status()}
function renderPoints(){const p=points();$('[data-points]').textContent=p;const track=$('[data-points-track]');track.innerHTML=Array.from({length:12},(_,i)=>`<i class="${i<p?'is-on':''}"></i>`).join('');$('[data-points-copy]').textContent=p>=12?'12 / 12. United Merch reward je odemčený.':`Ještě ${12-p} bodů a odemykáš United Merch reward.`}
function renderBadges(){const unlocked=badgeDefs.filter(b=>b.test(data));const html=(arr)=>arr.map(b=>`<div class="badge ${b.test(data)?'':'is-locked'}"><span class="badge-icon">${b.icon}</span><div><b>${b.name}</b><small>${b.desc}</small></div></div>`).join('');$('[data-badges-preview]').innerHTML=html((unlocked.length?unlocked:badgeDefs).slice(0,5));$('[data-badge-cabinet]').innerHTML=html(badgeDefs)}
function renderGarage(){const grid=$('[data-garage-grid]');if(!data.cars.length){grid.innerHTML='<div class="garage-empty"><div><b>Garáž je zatím prázdná.</b><br><small>Přidej svoje první E36. Pak ho můžeš napárovat na rezervaci.</small></div></div>';renderCarSelect();return}grid.innerHTML=data.cars.map(c=>`<article class="car-card"><div class="car-photo">${c.photos?.[0]?`<img src="${c.photos[0]}" alt="${esc(c.nickname||c.model)}">`:'<div class="car-photo-placeholder">E36</div>'}${c.primary?'<span class="car-primary">HLAVNÍ AUTO</span>':''}</div><div class="car-body"><small>${esc(c.body)} · ${esc(c.year||'')}</small><h3>${esc(c.nickname||c.model)}</h3><p>${esc(c.model)}${c.color?' · '+esc(c.color):''}</p><div class="car-actions"><button data-primary-car="${c.id}">${c.primary?'Hlavní':'Nastavit hlavní'}</button><button data-delete-car="${c.id}">Odebrat</button></div></div></article>`).join('');$$('[data-primary-car]').forEach(b=>b.onclick=async()=>{data.cars.forEach(c=>c.primary=c.id===b.dataset.primaryCar);await commit('Hlavní auto změněno')});$$('[data-delete-car]').forEach(b=>b.onclick=async()=>{if(!confirm('Odebrat auto z garáže?'))return;const removedId=b.dataset.deleteCar;data.cars=data.cars.filter(c=>c.id!==removedId);if(firebase&&currentUser)await firebase.deleteDoc(firebase.doc(firebase.db,'members',currentUser.uid,'cars',removedId));if(data.cars.length&&!data.cars.some(c=>c.primary))data.cars[0].primary=true;await commit('Auto odebráno')});renderCarSelect()}
function renderCarSelect(){const s=$('[data-car-select]');if(!s)return;s.innerHTML=data.cars.length?data.cars.map(c=>`<option value="${c.id}">${esc(c.nickname||c.model)} · ${esc(c.body)}</option>`).join(''):'<option value="">Nejdřív přidej auto do garáže</option>'}
function renderHistory(){const grid=$('[data-history-grid]');grid.innerHTML=data.history.map(h=>`<button class="history-year ${h.attended?'is-attended':''}" data-history-year="${h.year}"><div class="history-year-number">${h.year}</div><div class="history-year-status"><div><b>${h.attended?'ÚČAST PŘIDÁNA':'NEBYL/A JSEM'}</b><small>${h.attended?(h.verified?'Ověřeno United týmem':'Čeká na ověření'):'Klikni pro přidání'}</small></div><span class="history-check">${h.attended?'✓':'+'}</span></div></button>`).join('');$$('[data-history-year]').forEach(b=>b.onclick=async()=>{const h=data.history.find(x=>x.year===+b.dataset.historyYear);h.attended=!h.attended;if(!h.attended){h.verified=false;h.winner=false}await commit(h.attended?`United ${h.year} přidáno do historie`:`United ${h.year} odebráno`)})}
function renderReservation(){const r=data.reservation;const miniStatus=$('[data-reservation-status]'),year=$('[data-res-year]'),title=$('[data-res-title]'),car=$('[data-res-car]');if(!r){miniStatus.textContent='Žádná aktivní';year.textContent='—';title.textContent='Příští United';car.textContent='Vyber auto z garáže při potvrzení rezervace.';$('[data-reservation-state-label]').textContent='Bez aktivní rezervace';$('[data-reservation-year]').textContent='—';$('[data-reservation-title]').textContent='Příští E36 United';$('[data-reservation-summary]').innerHTML='';return}miniStatus.textContent='Uloženo';year.textContent=r.year||'NEXT';title.textContent=r.title||'United rezervace';car.textContent=r.carSnapshot?`${r.carSnapshot.nickname||r.carSnapshot.model} · ${r.carSnapshot.body}`:'Auto není vybrané';$('[data-reservation-state-label]').textContent='Rezervace uložena';$('[data-reservation-year]').textContent=r.year||'NEXT';$('[data-reservation-title]').textContent=r.title||'E36 United';$('[data-reservation-description]').textContent='Tento přehled je napárovaný na konkrétní snapshot auta z tvojí garáže.';$('[data-reservation-summary]').innerHTML=`<div><small>AUTO</small><b>${esc(r.carSnapshot?.nickname||r.carSnapshot?.model||'—')}</b></div><div><small>POSÁDKA</small><b>${esc(r.crew)} osoby</b></div><div><small>UBYTOVÁNÍ</small><b>${esc(r.sleep)}</b></div><div><small>SHOW & SHINE</small><b>${esc(r.showshine)}</b></div>`}
function renderRewards(){const p=points(),life=lifetimePoints();$('[data-reward-score]').textContent=p;const lock=$('[data-reward-lock]');lock.classList.toggle('is-unlocked',p>=12);lock.querySelector('span').textContent=p>=12?'UNLOCKED':'LOCKED';$('[data-reward-remaining]').textContent=p>=12?'United Merch reward je aktivní':`${12-p} bodů zbývá`;$('[data-points-ledger]').innerHTML=`<div class="ledger-item"><span>OVĚŘENÁ ÚČAST</span><b>+${portalConfig.points.attendance} body</b><small>Za každý potvrzený United.</small></div><div class="ledger-item"><span>SHOW & SHINE WIN</span><b>+${portalConfig.points.showShineWin} body</b><small>Po potvrzení výsledku organizátorem.</small></div><div class="ledger-item"><span>LIFETIME SCORE</span><b>${life} bodů</b><small>Celoživotní skóre se nemaže po rewardu.</small></div>`;const perks=[['⚡','Early registration','Členové dostanou registraci dřív.',verified()>=1],['◆','Member-only United Merch','Přístup k vybraným dropům.',verified()>=1],['12','United Merch reward','Odměna po dosažení 12 / 12.',p>=12],['★','Community voting','Hlasování o vybraných aktivitách.',verified()>=3],['⌁','Priority accommodation','Dřívější přístup k vybranému ubytování.',verified()>=5]];$('[data-perks-list]').innerHTML=perks.map(x=>`<div class="perk ${x[3]?'':'is-locked'}"><i>${x[0]}</i><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]?'ACTIVE':'LOCKED'}</span></div>`).join('')}

$('[data-reservation-form]').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),car=data.cars.find(c=>c.id===fd.get('carId'));if(!car)return toast('Nejdřív přidej auto do garáže.');data.reservation={year:'NEXT',title:'Příští E36 United',carId:car.id,carSnapshot:{id:car.id,nickname:car.nickname,model:car.model,body:car.body,year:car.year,color:car.color,photo:car.photos?.[0]||''},crew:+fd.get('crew'),sleep:fd.get('sleep'),showshine:fd.get('showshine'),note:fd.get('note'),status:'saved',updatedAt:new Date().toISOString()};await commit('Rezervace uložena · potvrzení připraveno')});
const carModal=$('[data-car-modal]');$('[data-open-car]').onclick=()=>{carModal.hidden=false;document.body.classList.add('modal-open')};$$('[data-close-car]').forEach(b=>b.onclick=()=>{carModal.hidden=true;document.body.classList.remove('modal-open')});
$('[data-car-form]').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),files=[...e.currentTarget.elements.photos.files].slice(0,3);const photos=[];for(const f of files)photos.push(await compressImage(f));const car={id:uid(),nickname:fd.get('nickname'),body:fd.get('body'),model:fd.get('model'),year:fd.get('year'),color:fd.get('color'),plate:fd.get('plate'),primary:fd.get('primary')==='on'||!data.cars.length,photos};if(car.primary)data.cars.forEach(c=>c.primary=false);data.cars.push(car);carModal.hidden=true;document.body.classList.remove('modal-open');e.currentTarget.reset();await commit('Auto přidáno do garáže')});
async function compressImage(file){return await new Promise((resolve,reject)=>{const img=new Image,reader=new FileReader;reader.onload=()=>img.src=reader.result;reader.onerror=reject;img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.58))};reader.readAsDataURL(file)})}

// Mobile nav
const menuBtn=$('.menu-btn'),nav=$('.nav-links');if(menuBtn&&nav)menuBtn.addEventListener('click',()=>{const o=document.body.classList.toggle('menu-open');menuBtn.setAttribute('aria-expanded',String(o));nav.classList.toggle('open',o)});

initFirebase().then(()=>{if(!firebaseReady){showAuth();renderAll()}});
