import {test,expect} from '@playwright/test';
import {commandFixture} from './command-fixture.mjs';
import {arrivalsRuntime,seedArrivals,EVENT} from '../helpers/arrivals-runtime.mjs';
import {routeArrivals} from '../../worker/domains/arrivals.js';
import {getAdminLive,getMemberLive,getLiveState,searchLiveMembers,startLiveEntry,saveJudgeScore,competitionCarMedia,createCompetitionCar} from '../../worker/domains/live.js';
import {readFileSync} from 'node:fs';
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type, If-Match, Idempotency-Key','Access-Control-Allow-Methods':'GET, POST, PUT, PATCH, OPTIONS'};
for(const width of [360,390,820,1440])for(const theme of ['light','dark'])test(`participant and gate ${width} ${theme}`,async({page},info)=>{
 await page.route('https://**/*',route=>route.abort());
 const r=arrivalsRuntime();await seedArrivals(r);r.db.prepare('UPDATE events SET live_enabled=1 WHERE id=?').run(EVENT);
 r.db.exec("INSERT INTO car_photos(id,car_id,r2_key,mime_type) VALUES('picker-photo','car-paid','synthetic-only','image/png')");
 const c=await commandFixture(page,{runtime:r});let failList=false;
 await page.route('https://api.e36united.cz/api/**',async route=>{
  const q=route.request(),u=new URL(q.url());if(!u.pathname.includes('/live')&&!u.pathname.includes('/arrivals'))return route.fallback();
  if(q.method()==='OPTIONS')return route.fulfill({status:204,headers});
  if(failList&&(u.pathname.endsWith('/members')||u.pathname.endsWith('/search')))return route.fulfill({status:503,headers,json:{message:'Izolovaná chyba načítání'}});
  if(u.pathname.endsWith('/media')||u.pathname.endsWith('/photo'))return route.fulfill({status:200,headers,contentType:'image/png',body:readFileSync(new URL('../../united-logo-blue-silver-transparent.png',import.meta.url))});
  const request=new Request(q.url(),{method:q.method(),headers:q.headers(),...(q.postDataBuffer()?{body:q.postDataBuffer()}: {})});let result;
  if(u.pathname.includes('/arrivals'))result=await routeArrivals({request,url:u,env:r.env,auth:{uid:'a'},origin:u.origin});
  else if(u.pathname==='/api/admin/live')result=await getAdminLive(r.env,u,u.origin);
  else if(u.pathname==='/api/live/state')result=await getLiveState(r.env,{uid:'a'},u,u.origin);
  else if(u.pathname==='/api/live')result=await getMemberLive(r.env,{uid:'a'},u.origin);
  else if(u.pathname.endsWith('/members'))result=await searchLiveMembers(r.env,EVENT,u,u.origin);
  else if(u.pathname.endsWith('/start'))result=await startLiveEntry(request,r.env,{uid:'a'},EVENT,u.origin);
  else if(u.pathname.endsWith('/cars'))result=await createCompetitionCar(request,r.env,{uid:'a'},EVENT,null,u.origin);
  else if(u.pathname.includes('/judge/scores/'))result=await saveJudgeScore(request,r.env,{uid:'a'},u.pathname.split('/').at(-1),u.origin);
  else return route.fulfill({status:404,headers,json:{error:'isolated_unhandled'}});
  return route.fulfill({status:result.status,headers,body:await result.text()});
 });
 try{
  await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme});await page.addInitScript(theme=>{if(window===window.top)localStorage.setItem('e36UnitedAppearance',theme)},theme);
  await page.goto('/admin.html?section=live&event='+EVENT);await page.locator('[data-admin-live-entry-confirm]').click();
  await page.locator('[data-live-select-category=Sedan]').click();await page.locator('[data-live-choose-member]').click();
  await expect(page.locator('[data-live-select-member="car:car-paid"]')).toBeVisible();
  await expect(page.locator('[data-live-camera]')).toHaveCount(0);
  await expect(page.locator('h2').filter({hasText:'Vybrat účastníka'})).toHaveCount(1);
  await page.screenshot({path:info.outputPath('participants.png'),fullPage:true});
  failList=true;await page.locator('[data-live-member-search] button').click();await expect(page.locator('[data-live-member-results]')).toContainText('Izolovaná chyba');failList=false;
  await page.locator('[data-live-choose-member]').click();await page.locator('[data-live-select-member="car:car-paid"]').click();
  await expect(page.locator('[data-live-start]')).toBeEnabled();await page.screenshot({path:info.outputPath('confirm-car.png'),fullPage:true});
  await page.locator('[data-live-start]').click();await expect(page.locator('[data-live-judge-form]')).toBeVisible();
  expect(r.db.prepare('SELECT COUNT(*) n FROM event_arrivals').get().n).toBe(0);
  await page.locator('[data-live-subview=results]').click();await page.locator('[data-live-subview=workflow]').click();await expect(page.locator('[data-live-judge-form]')).toBeVisible();
  await page.locator('[data-admin-live-tab=arrivals]').click();await expect(page.locator('[data-gate-find]')).toBeVisible();
  await page.screenshot({path:info.outputPath('gate-overview.png'),fullPage:true});
  await page.locator('[data-gate-find]').click();await expect(page.locator('[data-gate-pick="member:fixture-paid"]')).toBeVisible();
  await page.screenshot({path:info.outputPath('gate-search.png'),fullPage:true});
  await page.locator('[data-gate-pick="member:fixture-paid"]').click();await expect(page.locator('[name=crew]')).toHaveValue('2');
  await page.locator('[data-gate-crew="1"]').click();await expect(page.locator('[name=crew]')).toHaveValue('3');
  expect(r.db.prepare('SELECT COUNT(*) n FROM event_arrivals').get().n).toBe(0);
  await page.locator('.gate-confirm-actions button[type=submit]').evaluate(el=>el.scrollIntoView({block:'center'}));await page.screenshot({path:info.outputPath('gate-card.png')});
  const b=await page.locator('.gate-confirm-actions button[type=submit]').boundingBox();const nav=await page.locator('[data-admin-live-tab=arrivals]').boundingBox();expect(b.y+b.height).toBeLessThanOrEqual(nav.y);
  await page.locator('[data-gate-cancel]').click();await expect(page.locator('[data-gate-find]')).toBeVisible();
  expect(c.observations.pageErrors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 }finally{await page.close();r.db.close()}
});
test('guest creation, gate with LIVE off, errors and private exports',async({page},info)=>{
 await page.route('https://**/*',route=>route.abort());
 const r=arrivalsRuntime();await seedArrivals(r);r.db.prepare('UPDATE events SET live_enabled=1 WHERE id=?').run(EVENT);
 r.db.exec("INSERT INTO car_photos(id,car_id,r2_key,mime_type) VALUES('picker-photo','car-paid','synthetic-only','image/png')");
 const c=await commandFixture(page,{runtime:r});let failList=false;
 await page.route('https://api.e36united.cz/api/**',async route=>{
  const q=route.request(),u=new URL(q.url());if(!u.pathname.includes('/live')&&!u.pathname.includes('/arrivals'))return route.fallback();
  if(q.method()==='OPTIONS')return route.fulfill({status:204,headers});
  if(failList&&(u.pathname.endsWith('/members')||u.pathname.endsWith('/search')))return route.fulfill({status:503,headers,json:{message:'Izolovaná chyba načítání'}});
  if(u.pathname.endsWith('/media')||u.pathname.endsWith('/photo'))return route.fulfill({status:200,headers,contentType:'image/png',body:readFileSync(new URL('../../united-logo-blue-silver-transparent.png',import.meta.url))});
  const request=new Request(q.url(),{method:q.method(),headers:q.headers(),...(q.postDataBuffer()?{body:q.postDataBuffer()}: {})});let result;
  if(u.pathname.includes('/arrivals'))result=await routeArrivals({request,url:u,env:r.env,auth:{uid:'a'},origin:u.origin});
  else if(u.pathname==='/api/admin/live')result=await getAdminLive(r.env,u,u.origin);
  else if(u.pathname==='/api/live/state')result=await getLiveState(r.env,{uid:'a'},u,u.origin);
  else if(u.pathname==='/api/live')result=await getMemberLive(r.env,{uid:'a'},u.origin);
  else if(u.pathname.endsWith('/members'))result=await searchLiveMembers(r.env,EVENT,u,u.origin);
  else if(u.pathname.endsWith('/start'))result=await startLiveEntry(request,r.env,{uid:'a'},EVENT,u.origin);
  else if(u.pathname.endsWith('/cars'))result=await createCompetitionCar(request,r.env,{uid:'a'},EVENT,null,u.origin);
  else if(u.pathname.includes('/judge/scores/'))result=await saveJudgeScore(request,r.env,{uid:'a'},u.pathname.split('/').at(-1),u.origin);
  else return route.fulfill({status:404,headers,json:{error:'isolated_unhandled'}});
  return route.fulfill({status:result.status,headers,body:await result.text()});
 });

 try{
  await page.setViewportSize({width:820,height:900});await page.addInitScript(()=>{if(window===window.top)localStorage.setItem('e36UnitedAppearance','dark')});
  await page.goto('/admin.html?section=live&event='+EVENT);await page.locator('[data-admin-live-entry-confirm]').click();
  await page.locator('[data-live-select-category=Sedan]').click();await page.locator('[data-live-choose-member]').click();
  await page.locator('[data-live-new-car]').click();await page.locator('[name=participantName]').fill('Nový host bez účtu');
  await page.locator('[data-live-new-car-form] [name=model]').fill('BMW 328i samostatné auto');
  await page.locator('[data-live-new-car-form] button[type=submit]').click();await expect(page.locator('.admin-live-selected')).toContainText('Nový host bez účtu');
  await expect(page.locator('[data-live-start]')).toBeEnabled();await page.locator('[data-live-start]').click();await expect(page.locator('[data-live-judge-form]')).toBeVisible();
  for(const key of ['overall','condition','cohesion','originality'])await page.locator(`[data-live-judge-criterion=${key}][data-live-judge-score="8"]`).click();
  await page.locator('[data-live-judge-submit]').click();await expect(page.locator('[data-live-judge-summary]')).toContainText('Hodnocení potvrzeno');
  expect(r.db.prepare('SELECT COUNT(*) n FROM event_arrivals').get().n).toBe(0);
  r.db.prepare('UPDATE events SET live_enabled=0 WHERE id=?').run(EVENT);
  await page.locator('[data-admin-live-more-toggle]').click();await page.locator('[data-admin-live-exit]').click();
  await page.goto('/admin.html?section=arrivals&event='+EVENT);await expect(page.locator('[data-gate-find]')).toBeVisible();
  await page.locator('[data-gate-find]').click();await expect(page.locator('[data-gate-pick="member:fixture-paid"]')).toBeVisible();
  failList=true;await page.locator('[data-gate-lookup] button').click();await expect(page.locator('.gate-card')).toContainText('Seznam se nepodařilo načíst');failList=false;
  await page.locator('[data-gate-lookup] button').click();
  const guest=r.db.prepare("SELECT id FROM live_competition_cars WHERE participant_name='Nový host bez účtu'").get().id;
  await page.locator('[data-gate-pick="car:'+guest+'"]').click();await expect(page.locator('[name=carId]')).toHaveValue(guest);
  await page.locator('.gate-confirm-actions button[type=submit]').evaluate(el=>el.scrollIntoView({block:'center'}));
  await page.screenshot({path:info.outputPath('guest-gate-tablet.png')});
  await page.locator('.gate-confirm-actions button[type=submit]').click();await expect(page.locator('.gate-card h2')).toContainText('Příjezd potvrzen');
  expect(r.db.prepare("SELECT COUNT(*) n FROM event_payments WHERE method='cash'").get().n).toBe(1);
  expect(r.db.prepare('SELECT COUNT(*) n FROM live_competition_cars').get().n).toBe(1);
  await page.locator('[data-gate-next]').click();await page.locator('.gate-more summary').click();
  const popupPromise=page.waitForEvent('popup');await page.locator('[data-gate-print]').click();const popup=await popupPromise;
  await expect(popup.locator('h1')).toContainText('LOCAL-ARRIVALS-V1');await expect(popup.locator('table')).toContainText('Nový host bez účtu');
  await popup.screenshot({path:info.outputPath('private-print.png'),fullPage:true});await popup.close();
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-gate-csv]').click();expect((await downloadPromise).suggestedFilename()).toMatch(/\.csv$/);
  r.db.prepare("UPDATE reservations SET admission_czk=NULL WHERE id='reservation-paid'").run();
  await page.locator('[data-gate-find]').click();await page.locator('[data-gate-pick="member:fixture-paid"]').click();
  await expect(page.locator('[role=alert]')).toContainText('samostatně evidované vstupné');await expect(page.locator('.gate-confirm-actions button[type=submit]')).toBeDisabled();
  await expect(page.locator('[data-gate-price-detail="reservation-paid"]')).toBeVisible();
  expect(c.observations.pageErrors).toEqual([]);
 }finally{await page.close();r.db.close()}
});
