import test from 'node:test';
import assert from 'node:assert/strict';
import {merchRuntime} from './helpers/merch-runtime.mjs';
import {getCatalog,quotation,createOrder,readOrder,changeOrder,saveAddress,saveProduct,listOrders} from '../worker/domains/merch/service.js';
import {projectOrder} from '../worker/domains/merch/model.js';
import {deliverMerchEmail,routeMerch,publicMerch} from '../worker/domains/merch/index.js';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {requireAdmin} from '../worker/auth/admin.js';
const change=(env,o,action,extra={})=>changeOrder(env,'admin',o.id,{revision:o.revision,operationKey:crypto.randomUUID(),action,...extra},true);
const date=new Date().toISOString().slice(0,10);
test('confirmed discount and Czech shipping are calculated on server without spending points',async t=>{
 const r=await merchRuntime();t.after(r.close);r.db.prepare("INSERT INTO united_points_ledger(id,member_id,delta,source_type,source_key,reason) VALUES('p','member',12,'fixture','fixture','Isolated')").run();r.db.prepare("UPDATE merch_config SET data=json_set(data,'$.discountBasisPoints',1000)").run();
 const q=await quotation(r.env,'member',{...r.input,shipping:'address',address:{...r.input.address,phone:'+420777000000',street:'Test 1',city:'Praha',postalCode:'11000'}});assert.equal(q.quote.discountMinor,8900);assert.equal(q.quote.shippingMinor,12900);assert.equal(q.quote.totalMinor,93000);assert.equal(r.db.prepare('SELECT SUM(delta) n FROM united_points_ledger').get().n,12);
});
test('concurrent admin operations use compare-and-swap and never double-record money',async t=>{
 const r=await merchRuntime();t.after(r.close);const o=await r.order();const results=await Promise.allSettled([change(r.env,o,'payment',{amountMinor:10000,date}),change(r.env,o,'payment',{amountMinor:20000,date})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await readOrder(r.env,o.id)).state.payments.length,1);
});
test('uploaded photo is private until publication and remains readable for archived orders',async t=>{
 const r=await merchRuntime();t.after(r.close);const media=new Map();r.env.MEDIA={put:async(k,b)=>media.set(k,b),get:async k=>media.has(k)?{body:media.get(k)}:null,delete:async k=>media.delete(k)};
 const form=new FormData();form.set('file',new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=','base64')],'fixture.png',{type:'image/png'}));const raw=new Request('https://api.e36united.cz/api/admin/merch/media',{method:'POST',body:form});const bytes=await raw.arrayBuffer(),request=new Request(raw.url,{method:'POST',headers:{'Content-Type':raw.headers.get('Content-Type'),'Content-Length':String(bytes.byteLength)},body:bytes});
 const response=await routeMerch({request,url:new URL(request.url),env:r.env,auth:{uid:'admin'},origin:'https://e36united.cz'},true),uploaded=await response.json();assert.equal(response.status,200);const url=new URL('https://api.e36united.cz/api/merch/media/'+uploaded.image.slice(3));assert.equal((await publicMerch(r.env,url)).status,404);
 const p=(await getCatalog(r.env,true)).products[0];await saveProduct(r.env,'admin',{...p,variants:p.variants.map(v=>({...v,image:uploaded.image}))});assert.equal((await publicMerch(r.env,url)).status,200);const updated=(await getCatalog(r.env,true)).products[0];await saveProduct(r.env,'admin',{...updated,status:'archived'});assert.equal((await publicMerch(r.env,url)).status,200);
});
test('additive migration preserves populated registration data, indexes and FK',()=>{
 const db=new DatabaseSync(':memory:');try{
 const schema=readFileSync(new URL('../db/schema.sql',import.meta.url),'utf8'),migration=readFileSync(new URL('../db/migrations/2026-09-24-merch.sql',import.meta.url),'utf8');
 db.exec(schema.slice(0,schema.indexOf('-- Apply once, before the Worker.')));
 db.exec("INSERT INTO members(id,member_code,email,name) VALUES('m','M','m@example.invalid','Member'); INSERT INTO events(id,year,title) VALUES('event',2026,'Existing'); INSERT INTO reservations(id,member_id,event_id,status,amount_due_czk,amount_paid_czk,payment_vs) VALUES('r','m','event','approved',2440,1000,'2026000001')");
 const before=db.prepare('SELECT * FROM reservations').all(),objects=db.prepare("SELECT name,sql FROM sqlite_master WHERE type IN ('index','trigger') ORDER BY name").all();
 db.exec(migration);assert.deepEqual(db.prepare('SELECT * FROM reservations').all(),before);for(const obj of objects)assert.equal(db.prepare('SELECT sql FROM sqlite_master WHERE name=?').get(obj.name).sql,obj.sql);
 assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(JSON.parse(db.prepare('SELECT data FROM merch_config').get().data).paused,true);
 assert.throws(()=>db.prepare("INSERT INTO merch_addresses VALUES('missing','{}','now')").run(),/FOREIGN KEY/);
 }finally{db.close();}
});
test('merch and registration variable symbols cannot collide in either allocator',async t=>{
 const r=await merchRuntime();t.after(r.close);const o=await r.order();
 assert.throws(()=>r.db.prepare("INSERT INTO reservations(id,member_id,event_id,payment_vs) VALUES('r','member','united-2026',?)").run(o.variableSymbol),/payment_vs_collision/);
 r.db.prepare("INSERT INTO reservations(id,member_id,event_id,payment_vs) VALUES('r','member','united-2026','2026000001')").run();
 assert.throws(()=>r.db.prepare("INSERT INTO merch_orders(id,member_id,request_key,request_hash,payment_vs,snapshot,state,created_at,expires_at) SELECT 'collision',member_id,'collision',request_hash,'2026000001',snapshot,state,created_at,expires_at FROM merch_orders LIMIT 1").run(),/payment_vs_collision/);
 assert.throws(()=>r.db.prepare("UPDATE reservations SET payment_vs=? WHERE id='r'").run(o.variableSymbol),/payment_vs_collision/);
 assert.equal(r.db.prepare("SELECT amount_paid_czk FROM reservations WHERE id='r'").get().amount_paid_czk,0);
});
test('active members cannot administer or change money; inactive members cannot order',async t=>{
 const r=await merchRuntime();t.after(r.close);const o=await r.order();assert.equal(await requireAdmin(r.env,{uid:'member'}),null);assert.ok(await requireAdmin(r.env,{uid:'admin'}));
 await assert.rejects(changeOrder(r.env,'member',o.id,{operationKey:'illegal',revision:o.revision,action:'paid'}),/administrátora/);
 r.db.prepare("UPDATE members SET status='inactive' WHERE id='other'").run();const request=new Request('https://api.e36united.cz/api/merch/orders');assert.equal((await routeMerch({request,url:new URL(request.url),env:r.env,auth:{uid:'other'},origin:'https://e36united.cz'})).status,403);
});
test('refund projection and list filters agree; correction keeps ledger history',async t=>{
 const r=await merchRuntime();t.after(r.close);let o=await r.order();o=await change(r.env,o,'paid',{date});o=await change(r.env,o,'refund',{amountMinor:10000,reason:'Vráceno ručně'});assert.equal(o.payment.remainingMinor,10000);assert.equal((await listOrders(r.env,{filter:'unpaid'})).orders[0].id,o.id);assert.equal((await listOrders(r.env,{filter:'fulfill'})).orders.length,0);
 await assert.rejects(change(r.env,o,'void-payment',{paymentId:o.state.payments[0].id,reason:'Chybné datum'}),/refundace/);
 o=await change(r.env,o,'payment',{amountMinor:10000,date});assert.equal(o.payment.status,'paid');
});
test('reading email status cannot send or mutate the outbox',async t=>{
 const r=await merchRuntime();t.after(r.close);const o=await r.order(),request=new Request('https://api.e36united.cz/api/admin/merch/orders/'+o.id+'/email');const response=await routeMerch({request,url:new URL(request.url),env:r.env,auth:{uid:'admin'},origin:'https://e36united.cz'},true);assert.equal((await response.json()).messages[0].status,'pending');assert.equal(r.db.prepare('SELECT status FROM merch_outbox').get().status,'pending');
});
test('merch migration, defaults, FK and stable catalog IDs',async t=>{const r=await merchRuntime();t.after(r.close);const c=await getCatalog(r.env);assert.equal(c.products.length,6);assert.equal(c.products.flatMap(p=>p.variants).length,10);assert.equal(c.products[0].variants[0].priceMinor,89000);assert.deepEqual(r.db.prepare('PRAGMA foreign_key_check').all(),[]);});
test('authoritative quote ignores forged money and merges same sizes only',async t=>{const r=await merchRuntime();t.after(r.close);await assert.rejects(quotation(r.env,'member',{...r.input,totalMinor:1,discountMinor:89000}),/server/);const q=await quotation(r.env,'member',{...r.input,lines:[...r.input.lines,...r.input.lines,{variantId:'u-polo-navy',size:'L',quantity:1}]});assert.equal(q.quote.totalMinor,267000);assert.equal(q.quote.discountMinor,0);assert.equal(q.quote.lines.length,2);});
test('unavailable, missing image, missing price and invalid sizes cannot be ordered',async t=>{const r=await merchRuntime();t.after(r.close);const p=(await getCatalog(r.env,true)).products[0];for(const field of [{priceMinor:null},{availability:'unavailable'},{image:''},{sizes:['S']}]){const copy=structuredClone(p);Object.assign(copy.variants[0],field);r.db.prepare('UPDATE merch_products SET data=? WHERE id=?').run(JSON.stringify(copy),p.id);await assert.rejects(quotation(r.env,'member',r.input));}});
test('double create is atomic and changed price requires new confirmation',async t=>{const r=await merchRuntime();t.after(r.close);const q=await quotation(r.env,'member',r.input),input={...r.input,requestKey:'same-request',quoteHash:q.hash,termsAccepted:true,termsVersion:q.quote.termsVersion};const orders=await Promise.all([createOrder(r.env,'member',input),createOrder(r.env,'member',input)]);assert.equal(orders[0].id,orders[1].id);assert.equal(r.db.prepare('SELECT COUNT(*) n FROM merch_orders').get().n,1);assert.equal(r.db.prepare('SELECT COUNT(*) n FROM merch_outbox').get().n,1);r.db.prepare("UPDATE merch_products SET data=json_set(data,'$.variants[0].priceMinor',90000),revision=revision+1 WHERE id='united-u-polo'").run();await assert.rejects(createOrder(r.env,'member',{...input,requestKey:'new-request'}),/změnily/);});
test('own order, address and recovery endpoint remain UID scoped',async t=>{const r=await merchRuntime();t.after(r.close);const o=await r.order();await assert.rejects(readOrder(r.env,o.id,'other'),/nalezena/);assert.equal((await listOrders(r.env,{member:'other'})).orders.length,0);const request=new Request('https://api.e36united.cz/api/merch/requests/unknown');const response=await routeMerch({request,url:new URL(request.url),env:r.env,auth:{uid:'other'},origin:'https://e36united.cz'});assert.equal((await response.json()).order,null);});
test('partial, remaining QR, duplicate paid, overpayment and refund history',async t=>{const r=await merchRuntime();t.after(r.close);let o=await r.order();assert.match(o.payment.spayd,/AM:890.00/);assert.match(o.payment.spayd,new RegExp('X-VS:'+o.variableSymbol));o=await change(r.env,o,'payment',{amountMinor:20000,date});assert.equal(o.payment.remainingMinor,69000);assert.match(o.payment.spayd,/AM:690.00/);o=await change(r.env,o,'paid',{date});o=await change(r.env,o,'paid',{date});assert.equal(o.state.payments.length,2);assert.equal(o.payment.spayd,null);o=await change(r.env,o,'payment',{amountMinor:1000,date});assert.equal(o.payment.overpaidMinor,1000);o=await change(r.env,o,'refund',{amountMinor:1000,reason:'Vrácen přeplatek'});assert.equal(o.payment.refundedMinor,1000);assert.equal(o.state.payments.length,3);});
test('expiry, late payment and explicit restoration preserve original amount',async t=>{const r=await merchRuntime();t.after(r.close);let o=await r.order();r.db.prepare("UPDATE merch_orders SET expires_at='2000-01-01T00:00:00.000Z' WHERE id=?").run(o.id);o=await readOrder(r.env,o.id);assert.equal(o.state.status,'expired');assert.equal(o.payment.spayd,null);o=await change(r.env,o,'payment',{amountMinor:89000,date});assert.equal(o.state.status,'expired');o=await change(r.env,o,'restore',{reason:'Úhrada doložena, zboží lze dodat',deliveryConfirmed:true});assert.equal(o.state.status,'new');});
test('partial expiry is manual; cancellation does not erase payment',async t=>{const r=await merchRuntime();t.after(r.close);let o=await r.order();o=await change(r.env,o,'payment',{amountMinor:10000,date});r.db.prepare("UPDATE merch_orders SET expires_at='2000-01-01T00:00:00.000Z' WHERE id=?").run(o.id);o=await readOrder(r.env,o.id);assert.equal(o.state.status,'new');assert.equal(o.payment.reviewRequired,true);o=await changeOrder(r.env,'member',o.id,{revision:o.revision,operationKey:'member-cancel',action:'cancel'});assert.equal(o.state.status,'new');assert.equal(o.state.requests[0].kind,'cancel');o=await change(r.env,o,'cancel');assert.equal(o.payment.paidMinor,10000);assert.equal(o.payment.spayd,null);});
test('snapshot survives catalog and default address changes',async t=>{const r=await merchRuntime();t.after(r.close);const o=await r.order();await saveAddress(r.env,'member',{name:'Changed',email:'new@example.invalid',phone:'+420777000000',street:'Test 1',city:'Praha',postalCode:'11000'});const p=(await getCatalog(r.env,true)).products[0];await saveProduct(r.env,'admin',{...p,status:'archived',name:'Changed'});const read=await readOrder(r.env,o.id,'member');assert.deepEqual(read.snapshot,o.snapshot);assert.throws(()=>r.db.prepare('UPDATE merch_orders SET snapshot=? WHERE id=?').run('{}',o.id),/immutable/);});
test('email failure keeps order and does not deliver duplicate',async t=>{const r=await merchRuntime();t.after(r.close);const o=await r.order();await deliverMerchEmail(r.env,o.id);assert.ok(['failed','uncertain'].includes(r.db.prepare('SELECT status FROM merch_outbox').get().status));assert.equal((await readOrder(r.env,o.id)).id,o.id);await deliverMerchEmail(r.env,o.id);assert.equal(r.db.prepare('SELECT COUNT(*) n FROM merch_outbox').get().n,1);});
test('new category and variant uniqueness, audit and pagination',async t=>{const r=await merchRuntime();t.after(r.close);const p=(await getCatalog(r.env,true)).products[0];await saveProduct(r.env,'admin',{...p,id:'new-product',category:'Nová kategorie',variants:[{...p.variants[0],id:'new-variant'}]});assert.ok((await getCatalog(r.env)).products.some(p=>p.category==='Nová kategorie'));await assert.rejects(saveProduct(r.env,'admin',{...p,id:'duplicate'}),/ID varianty/);assert.equal(r.db.prepare("SELECT COUNT(*) n FROM merch_audit WHERE action='product'").get().n,1);assert.deepEqual((await listOrders(r.env,{member:'member'})).orders,[]);});
test('withdrawal receipt and state change commit together',async t=>{const r=await merchRuntime();t.after(r.close);let o=await r.order();o=await changeOrder(r.env,'member',o.id,{revision:o.revision,operationKey:'withdraw',action:'withdraw',reason:'Odstupuji'});assert.equal(o.state.requests[0].kind,'withdraw');assert.equal(r.db.prepare('SELECT COUNT(*) n FROM merch_outbox').get().n,2);});
