import { apiRequest, apiMedia, apiUpload } from '../api.js?v=20260930-arrivals2';
import { adminState } from '../state.js?v=20260930-arrivals2';
import { escapeHtml as esc, toast } from '../ui.js?v=20260924-merch2';
import { createPhotoBatch, renderPhotoBatch } from '../../photo-batch.js?v=20260928-flow1';

const controllers=new Map(),owners=new WeakMap();
const czk=v=>v==null?'Cena není nastavená':new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(v);
const statuses={paid:'Zaplaceno',underpaid:'Částečně zaplaceno',unpaid:'Nezaplaceno',overpaid:'Přeplatek',not_required:'Bez doplatku'};
export function mountArrivals(root,eventId) {
  if(!root||!eventId||!adminState.currentUser)return;
  const key=adminState.currentUser.uid+':'+eventId;
  let c=controllers.get(key);if(!c){c=createArrivals(eventId,key);controllers.set(key,c)}
  const previous=owners.get(root);if(previous&&previous!==c)previous.unmount();owners.set(root,c);c.mount(root);return c;
}
export function initializeArrivals() {
  const load=()=>{if(adminState.activeAdminView==='arrivals')mountArrivals(document.querySelector('[data-admin-panel=arrivals]'),adminState.selectedEventId)};
  for(const name of ['admin:viewchange','admin:eventchanged'])window.addEventListener(name,load);
  window.addEventListener('admin:accesslost',()=>{for(const c of controllers.values())c.clear();controllers.clear()});
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-gate-open],[data-gate-reservation],[data-gate-arrival]');if(!b)return;document.querySelector('[data-reservation-drawer-close]:not(.admin-reservation-drawer-backdrop)')?.click();document.querySelector('[data-member-close]')?.click();document.querySelector('[data-portal-target=arrivals]')?.click();const c=mountArrivals(document.querySelector('[data-admin-panel=arrivals]'),adminState.selectedEventId);if(b.dataset.gateReservation)await c?.openReservation(b.dataset.gateReservation);if(b.dataset.gateArrival)await c?.openArrival(b.dataset.gateArrival)});
  return {load};
}
function createArrivals(eventId,key) {
  let root=null,data=null,members=[],selected=null,draft=null,confirmed=null,busy=false,filter='all',query='',message='',operation=null,stream=null,scanFrame=0,sequence=0,paymentFilter='all',bankReservation=null;
  const storage='e36United.arrivalDraft.'+key;
  try{const saved=JSON.parse(sessionStorage.getItem(storage)||'null');if(saved){draft=saved.draft;selected=saved.selected;operation=saved.operation;confirmed=saved.confirmed||null;bankReservation=saved.bankReservation||null}}catch{}
  const path='/api/admin/events/'+encodeURIComponent(eventId)+'/arrivals';
  const batch=createPhotoBatch({maxFiles:1,onNotice:toast,onChange:()=>renderPhotoBatch(root?.querySelector('[data-gate-photos]'),batch)});
  const persist=()=>{try{sessionStorage.setItem(storage,JSON.stringify({draft,selected,operation,confirmed,bankReservation}))}catch{}};
  const current=()=>adminState.currentUser?.uid+':'+adminState.selectedEventId===key;
  const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(String(value??''))}" ${extra}></label>`;
  function stopCamera(){cancelAnimationFrame(scanFrame);stream?.getTracks().forEach(t=>t.stop());stream=null}
  async function camera(){
    stopCamera();const captured=++sequence;
    try{
      if(!('BarcodeDetector' in window)){message='Tento prohlížeč neumí číst QR z kamery. Použij čtečku nebo ruční vyhledání.';render();return}
      const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});
      if(captured!==sequence||!current()){acquired.getTracks().forEach(t=>t.stop());return}
      stream=acquired;render();const video=root.querySelector('video');video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});
      async function frame(){if(!stream||!root?.isConnected||!root.getClientRects().length||!current()){stopCamera();return}try{const [code]=await detector.detect(video);if(code){stopCamera();await lookupQr(code.rawValue);return}}catch{}scanFrame=requestAnimationFrame(()=>void frame())}void frame();
    }catch{message='Kamera není dostupná. Použij vyhledávání nebo ruční QR.';render()}
  }
  async function load(){const captured=++sequence;try{const response=await apiRequest(path,{fresh:true});if(!current()||captured!==sequence)return;data=response;if(confirmed){confirmed=(await apiRequest(path+'/'+confirmed.id,{fresh:true})).arrival;if(!current()||captured!==sequence)return;persist()}render()}catch(e){if(!current())return;message=e.message;render()}}
  function start(member=null){
    stopCamera();selected=member;confirmed=null;operation=null;message='';batch.clear();
    const cars=member?JSON.parse(member.carsJson||'[]'):[],car=cars.find(c=>c.id===member?.registeredCarId)||cars[0];
    const rate=member?.reservationStatus==='approved'?member.admission_czk:data?.event.admission_onsite_czk;
    const due=member?.reservationStatus==='approved'?member.due:rate;
    draft={id:crypto.randomUUID(),memberId:member?.id||null,carId:car?.id||'',model:car?.model||'',body:car?.body||'Sedan',crew:member?.crew||1,cash:Math.max(0,(due||0)-(member?.paid||0)),free:false,acceptDebt:false,matchesReviewed:!!member};persist();render();root.querySelector('h2')?.focus();
  }
  function capture(){const f=root.querySelector('[data-gate-form]');if(!f||!draft)return;const values=Object.fromEntries(new FormData(f));Object.assign(draft,values);for(const name of ['crew','cash'])draft[name]=Number(values[name]||0);for(const name of ['free','acceptDebt','matchesReviewed','additionalCar'])draft[name]=f.elements[name]?.checked||false;persist()}
  function totals(){const registered=selected?.reservationStatus==='approved'&&!draft?.additionalCar,admission=registered?selected.admission_czk:data?.event.admission_onsite_czk,services=registered&&admission!=null?selected.due-admission:0,paid=registered?selected.paid:0,due=admission==null&&!draft?.free?null:services+(draft?.free?0:admission||0);return{admission,services,paid,due,balance:due==null?null:due-paid}}
  function moneyPanel(){const t=totals();return `<dl class="gate-money"><div><dt>Vstupné za auto</dt><dd>${draft.free?'FREE VSTUP':czk(t.admission)}</dd></div><div><dt>Ubytování a služby</dt><dd>${czk(t.services)}</dd></div><div><dt>Celkem</dt><dd>${czk(t.due)}</dd></div><div><dt>Uhrazeno</dt><dd>${czk(t.paid)}</dd></div><div><dt>${t.balance<0?'Přeplatek':'Doplatek'}</dt><dd>${czk(t.balance==null?null:Math.abs(t.balance))}</dd></div></dl>`}
  function photoControls(){return `<div class="gate-photo-actions"><label class="gate-button">Vyfotit auto<input data-gate-file type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></label><label class="gate-button gate-secondary">Vybrat z galerie<input data-gate-file type="file" accept="image/jpeg,image/png,image/webp"></label></div><div data-gate-photos></div>`}
  function form(){
    const cars=selected?JSON.parse(selected.carsJson||'[]'):[];
    return `<section class="gate-card"><header><small>${selected?'ČLEN · '+esc(selected.memberCode):'NOVÝ NÁVŠTĚVNÍK'}</small><h2 tabindex="-1">${esc(selected?.nickname||selected?.name||'Odbavení auta')}</h2><p>${selected?.reservationStatus==='approved'?'Schválená registrace':selected?.reservationStatus==='pending'?'Čekající registrace · sazba na místě':'Bez schválené registrace · sazba na místě'}${selected?.accommodation?' · '+esc(selected.accommodation):''}${selected?.arrival?' · '+esc(selected.arrival):''}</p></header><form data-gate-form><fieldset ${busy||operation?'disabled':''}><div class="gate-columns"><div>
      ${cars.length?`<label>Skutečné auto<select name="carId">${cars.map(c=>`<option value="${esc(c.id)}" ${draft.carId===c.id?'selected':''}>${esc(c.model)} · ${esc(c.body||'')}</option>`).join('')}<option value="" ${!draft.carId?'selected':''}>Přijel jiným autem</option></select></label>`:''}
      <div data-gate-new-car ${draft.carId?'hidden':''}>${field('model','Model / označení auta',draft.model)}<label>Karoserie<select name="body">${['Sedan','Coupé','Touring','Cabrio','Compact','Z3'].map(v=>`<option ${v===draft.body?'selected':''}>${v}</option>`).join('')}</select></label></div>
      <img data-gate-selected-photo alt="Vybrané auto" hidden>${field('plate','SPZ (nepovinná)',draft.plate)}${field('crew','Skutečný počet osob',draft.crew,'number','min="1" max="99" required')}${photoControls()}
      ${selected?`<details><summary>Další auto tohoto člena</summary><label class="gate-check"><input type="checkbox" name="additionalCar" ${draft.additionalCar?'checked':''}> Jde o další auto, nikoli opravu předchozího příjezdu. Sazba na místě.</label></details>`:`<details open><summary>Kontakt (nepovinný)</summary>${field('name','Jméno',draft.name)}${field('nickname','Přezdívka',draft.nickname)}${field('email','E-mail pro pozvánku',draft.email,'email')}${field('phone','Telefon',draft.phone,'tel')}<button data-gate-matches type="button">Ověřit možné shody</button><label class="gate-check"><input name="matchesReviewed" type="checkbox" ${draft.matchesReviewed?'checked':''}> Prověřil jsem možné shody / návštěvník je bez kontaktních údajů.</label><p data-gate-invite></p></details>`}
      </div><div><div data-gate-totals>${moneyPanel()}</div>${field('cash','Ponechaná hotovost po vrácení drobných (Kč)',draft.cash,'number','min="0" step="1" required')}<details ${draft.free?'open':''}><summary>FREE VSTUP</summary><label class="gate-check"><input name="free" type="checkbox" ${draft.free?'checked':''}> Odpustit pouze vstupné</label>${field('freeReason','Důvod',draft.freeReason)}<small>Úhrady nevracíme a ubytování zůstává k úhradě.</small></details><label class="gate-check"><input name="acceptDebt" type="checkbox" ${draft.acceptDebt?'checked':''}> Potvrzuji příjezd i se zbývajícím nedoplatkem.</label><button class="gate-primary" type="submit">Potvrdit příjezd</button></div></div></fieldset></form><button data-gate-cancel type="button" ${busy||operation?'disabled':''}>Zpět na přehled</button>${operation?'<p>Výsledek zatím není ověřený. Nevytvářej druhý příjezd.</p><button data-gate-reconcile type="button">Ověřit uložení / zopakovat stejný požadavek</button>':''}</section>`;
  }
  function saved(){const a=confirmed;return `<section class="gate-card"><h2 tabindex="-1">Příjezd ${a.arrived_at?'potvrzen':'nepotvrzen'}</h2><img data-gate-saved-photo alt="Fotografie skutečného auta" hidden><p>${esc(a.label)} · ${esc(a.model)} · ${esc(a.body)} · ${esc(a.arrived_at||'')}</p><p class="gate-payment" data-status="${esc(a.paymentStatus)}">${statuses[a.paymentStatus]} · ${a.balance<0?'přeplatek':'doplatek'} ${czk(Math.abs(a.balance))}</p><p>${a.crew} osob · celkem ${czk(a.due)} · uhrazeno ${czk(a.paid)}</p>${a.invitation_status?'<p>Pozvánka: '+esc(a.invitation_status)+'</p>':''}${['queued','failed'].includes(a.invitation_status)?'<button data-gate-invitation-retry type="button">Zkusit odeslat neodeslanou pozvánku</button>':''}${photoControls()}<button data-gate-photo-retry type="button">Uložit pouze fotografii</button><details><summary>Oprava / další úhrada</summary><form data-gate-correction><fieldset ${busy||operation?'disabled':''}>${field('crew','Skutečný počet osob',a.crew,'number','min="1" max="99"')}${field('amount','Nová přijatá částka (Kč)',0,'number','min="0"')}<label>Způsob<select name="method"><option value="cash">Hotovost</option><option value="bank">Banka</option></select></label><label>Opravit dřívější platbu<select name="reversesId"><option value="">Bez storna</option>${a.payments.filter(p=>!p.reverses_id&&!a.payments.some(x=>x.reverses_id===p.id)).map(p=>`<option value="${esc(p.id)}">Storno ${p.method==='cash'?'hotovosti':'banky'} ${czk(p.amount_czk)}</option>`).join('')}</select></label><details><summary>Opravit omylem zvolené auto</summary><label class="gate-check"><input name="correctCar" type="checkbox"> Změnit skutečné auto (nikoliv další vjezd)</label>${field('carId','ID jiného auta z garáže / soutěžního auta (volitelné)')}${field('model','Model',a.model)}<label>Karoserie<select name="body">${['Sedan','Coupé','Touring','Cabrio','Compact','Z3'].map(v=>`<option ${v===a.body?'selected':''}>${v}</option>`).join('')}</select></label>${field('plate','SPZ',a.plate)}</details>${field('reason','Důvod opravy / doplnění','','text','required')}<button type="submit" ${busy?'disabled':''}>Uložit opravu</button></fieldset></form></details>${operation?'<p>Výsledek opravy není ověřený.</p><button data-gate-reconcile type="button">Ověřit uložení / zopakovat stejný požadavek</button>':''}<button class="gate-primary" data-gate-next type="button" ${busy?'disabled':''}>Další příjezd</button></section>`}
  function list(){const count=data?.counts||{},all=data?.arrivals||[],pending=(data?.expected||[]).map(r=>({...r,id:r.reservationId,label:r.nickname||r.name,member_id:r.memberId,reservation_id:r.reservationId,registered:r.status==='approved',arrived_at:null,paymentStatus:r.paid>r.due?'overpaid':r.paid===r.due?'paid':r.paid?'underpaid':'unpaid'}));
    const visible=[...all,...pending].filter(a=>(filter==='all'||filter==='absent'&&!a.arrived_at||filter==='arrived'&&a.arrived_at||filter==='guest'&&!a.registered)&&(paymentFilter==='all'||a.paymentStatus===paymentFilter)&&[a.label,a.model,a.plate,a.email].join(' ').toLocaleLowerCase('cs').includes(query.toLocaleLowerCase('cs')));
    return `<div class="gate-actions"><button class="gate-primary" data-gate-scan type="button">▦ Skenovat QR</button><button data-gate-find type="button">Vyhledat člena</button><button data-gate-new type="button">＋ Nový příjezd</button></div><div class="gate-counts">${[['Čekáme',count.expected],['Dorazilo aut',count.arrived],['Bez registrace',count.unregistered],['Osob',count.people],['Hotovost na bráně',czk(count.cash||0)]].map(([k,v])=>`<span>${k}<strong>${v??'—'}</strong></span>`).join('')}</div>${stream?'<video autoplay muted playsinline></video><button data-gate-stop type="button">Zavřít kameru</button>':''}<details data-gate-search><summary>QR / ruční vyhledání</summary><form data-gate-lookup>${field('q','Jméno, přezdívka, e-mail nebo SPZ')}<button>Hledat</button></form><form data-gate-qr>${field('payload','Obsah členského QR')}<button>Načíst QR</button></form></details>${memberRows()}<nav class="gate-filters" aria-label="Příjezdy">${[['all','Všichni'],['absent','Nedorazili'],['arrived','Dorazili'],['guest','Bez registrace']].map(([k,v])=>`<button data-gate-filter="${k}" aria-pressed="${filter===k}">${v}</button>`).join('')}</nav><label>Platba<select data-gate-payment-filter>${[['all','Všechny platby'],...Object.entries(statuses)].map(([k,v])=>`<option value="${k}" ${k===paymentFilter?'selected':''}>${v}</option>`).join('')}</select></label>${field('filterQuery','Hledat v přehledu',query,'search','data-gate-filter-query')}<div class="gate-rows">${visible.map(a=>`<article>${a.hasPhoto?'<img data-gate-media="'+esc(path+'/'+a.id+'/photo')+'" alt="Auto" hidden>':''}<div><strong>${esc(a.label)}</strong><span>${esc(a.model||'Auto neuvedeno')}${a.plate?' · '+esc(a.plate):''}</span><small>${a.arrived_at?'Příjezd již evidován v '+esc(a.arrived_at):a.status==='pending'?'Čekající registrace · nepotvrzeno':'Očekávaný příjezd'} · ${statuses[a.paymentStatus]}</small></div><button ${a.arrived_at?'data-gate-detail="'+esc(a.id)+'"':'data-gate-member="'+esc(a.member_id)+'"'} type="button">${a.arrived_at?'Detail':'Odbavit'}</button>${!a.arrived_at?'<button data-gate-bank="'+esc(a.reservation_id)+'" type="button">Evidovat platbu</button>':''}</article>`).join('')||'<p>V tomto výběru nic není.</p>'}</div><button data-gate-export type="button">Export pro nouzovou obsluhu</button>`}
  function memberRows(){return members.length?`<section class="gate-matches"><h3>Možné shody</h3>${members.map(m=>`<button data-gate-pick="${esc(m.id)}" type="button">${esc(m.nickname||m.name)} · ${esc(m.email)} · ${m.reservationStatus==='approved'?'schválená registrace':'bez schválené registrace'}</button>`).join('')}</section>`:''}
  function render(){if(!root?.isConnected||!current())return;root.classList.add('gate-app');root.dataset.gateContext=key;root.innerHTML=`<header class="gate-heading"><div><small>${esc(data?.event.title||'Vybraný ročník')}</small><h1>Příjezdy</h1></div><button data-gate-refresh type="button">Obnovit přehled</button></header><p role="status" class="gate-message">${esc(message)}</p>${confirmed?saved():draft?form()+memberRows():bankReservation?`<section class="gate-card"><h2>Jednotlivá úhrada rezervace</h2><form data-gate-bank-form>${field('amount','Přijatá částka (Kč)','','number','min="1" required')}<label>Způsob<select name="method"><option value="bank">Banka</option><option value="cash">Hotovost</option></select></label>${field('reason','Poznámka / důvod','','text','required')}<button class="gate-primary" type="submit" ${busy?'disabled':''}>Uložit úhradu</button></form><button data-gate-next type="button">Zpět</button>${operation?'<button data-gate-reconcile type="button">Ověřit uložení</button>':''}</section>`:list()}`;renderPhotoBatch(root.querySelector('[data-gate-photos]'),batch);updateInvite();if(confirmed)void showPhoto();void showMedia();}
  async function showMedia(){
    const image=root?.querySelector('[data-gate-selected-photo]'),car=selected&&JSON.parse(selected.carsJson||'[]').find(c=>c.id===draft?.carId);
    if(image){image.hidden=true;delete image.dataset.gateMedia;if(car?.photoId)image.dataset.gateMedia=car.source==='competition'?'/api/admin/events/'+encodeURIComponent(eventId)+'/live/cars/'+encodeURIComponent(car.id)+'/media':'/api/admin/members/'+encodeURIComponent(selected.id)+'/media/cars/'+encodeURIComponent(car.id)+'/'+encodeURIComponent(car.photoId)}
    await Promise.all([...root.querySelectorAll('[data-gate-media]')].map(async img=>{const source=img.dataset.gateMedia;try{const blob=await apiMedia(source);if(!img.isConnected||source!==img.dataset.gateMedia)return;const url=URL.createObjectURL(blob);img.onload=img.onerror=()=>URL.revokeObjectURL(url);img.src=url;img.hidden=false}catch{/* Missing photo does not block admission. */}}));
  }
  function updateInvite(){const node=root?.querySelector('[data-gate-invite]');if(node)node.textContent=draft?.email?'Na '+draft.email+' připravíme jednu pozvánku k ověřenému propojení účasti.':'Bez e-mailu nevznikne účet ani pozvánka.'}
  async function lookupQr(payload){const r=await apiRequest(path+'/qr',{method:'POST',body:{payload}});members=r.members||[];if(members.length===1)start(members[0]);else{message='Člena se nepodařilo najít.';render()}}
  async function search(q){const r=await apiRequest(path+'/search?q='+encodeURIComponent(q));members=r.members||[];message=members.length?'Vyber existujícího člena, nebo pokračuj jako samostatný návštěvník.':'Nenalezena shoda.';render();root.querySelector('[data-gate-search]')?.setAttribute('open','')}
  async function showPhoto(){const image=root?.querySelector('[data-gate-saved-photo]'),id=confirmed?.id;if(!image||!id)return;try{const blob=await apiMedia(path+'/'+id+'/photo');if(!image.isConnected||confirmed?.id!==id)return;const url=URL.createObjectURL(blob);image.onload=()=>URL.revokeObjectURL(url);image.src=url;image.hidden=false}catch{/* Photo optional; arrival and payment remain confirmed. */}}async function upload(){if(!confirmed)return;busy=true;try{await batch.send((blob,item)=>apiUpload(path+'/'+confirmed.id+'/photo',blob,{method:'POST',uploadId:item.id}));}finally{busy=false;render()}}
  async function sendOperation(){
    if(busy||!operation)return;busy=true;render();const op=operation;
    try{
      let result=await apiRequest(path+op.suffix,{method:op.method,body:op.body,headers:{'Idempotency-Key':op.id,'If-Match':String(op.revision)}});
      if(!current())return;
      if(result.replayed){const id=result.operation?.entityId!==eventId?result.operation?.entityId:op.body.id||op.suffix.slice(1);if(id&&op.suffix!=='/reservation-payment')result=await apiRequest(path+'/'+id,{fresh:true})}
      if(result.arrival){confirmed=result.arrival;draft=null;message=result.alreadyArrived?'Příjezd již evidován. Další platba nebyla vytvořena.':'Příjezd potvrzen serverem.'}else{draft=null;message='Platba uložena.'}
      operation=null;bankReservation=null;persist();await load();
    }catch(e){if(!current())return;message=e.message;if(e.status&&e.status<500){operation=null;persist()}else message='Výsledek uložení není ověřený. Použij ověření; koncept a původní ID zůstávají.';
    }finally{busy=false;render()}
    if(confirmed&&batch.pending&&!operation)await upload();
  }
  async function reconcile(){if(!operation)return;const receipt=await apiRequest('/api/admin/operations/'+operation.id,{fresh:true});if(receipt.operation?.state==='confirmed'){const id=receipt.operation.entityId!==eventId?receipt.operation.entityId:operation.body.id||operation.body.arrivalId||operation.suffix.slice(1);if(id&&operation.suffix!=='/reservation-payment'){const response=await apiRequest(path+'/'+id,{fresh:true});confirmed=response.arrival;}draft=null;operation=null;bankReservation=null;persist();await load();if(confirmed&&batch.pending)await upload()}else await sendOperation()}
  async function submit(e){
    e.preventDefault();if(busy||!data||operation)return;
    try{
      if(e.target.matches('[data-gate-form]')){capture();operation={id:crypto.randomUUID(),revision:data.revision,suffix:'',method:'POST',body:{...draft}};persist();await sendOperation()}
      else if(e.target.matches('[data-gate-bank-form]')){const b=Object.fromEntries(new FormData(e.target));operation={id:crypto.randomUUID(),revision:data.revision,suffix:'/reservation-payment',method:'POST',body:{reservationId:bankReservation,amount:Number(b.amount),method:b.method,reason:b.reason}};persist();await sendOperation()}else if(e.target.matches('[data-gate-lookup]'))await search(new FormData(e.target).get('q'));
      else if(e.target.matches('[data-gate-qr]'))await lookupQr(new FormData(e.target).get('payload'));
      else if(e.target.matches('[data-gate-correction]')){const b=Object.fromEntries(new FormData(e.target));operation={id:crypto.randomUUID(),revision:data.revision,suffix:'/'+confirmed.id,method:'PATCH',body:{version:confirmed.version,crew:Number(b.crew),reason:b.reason,...(b.correctCar?{car:{id:b.carId,model:b.model,body:b.body,plate:b.plate}}:{}),...(b.reversesId?{payment:{reversesId:b.reversesId}}:Number(b.amount)>0?{payment:{amount:Number(b.amount),method:b.method}}:{})}};persist();await sendOperation()}
    }catch(error){message=error.message;render()}
  }
  async function click(e){const button=e.target.closest('button');if(!button||busy)return;
    try{
      if(button.hasAttribute('data-gate-refresh')){capture();await load()}
      else if(button.hasAttribute('data-gate-new'))start();
      else if(button.hasAttribute('data-gate-scan'))await camera();
      else if(button.hasAttribute('data-gate-stop')){stopCamera();render()}
      else if(button.hasAttribute('data-gate-find')){root.querySelector('[data-gate-search]').open=true;root.querySelector('[name=q]').focus()}
      else if(button.hasAttribute('data-gate-matches')){capture();await search(draft.email||draft.nickname||draft.name||'')}
      else if(button.dataset.gatePick)start(members.find(m=>m.id===button.dataset.gatePick));
      else if(button.dataset.gateMember){const r=await apiRequest(path+'/search?q='+encodeURIComponent((data.expected.find(a=>a.memberId===button.dataset.gateMember)||{}).name||''));start(r.members.find(m=>m.id===button.dataset.gateMember))}
      else if(button.dataset.gateDetail){confirmed=(await apiRequest(path+'/'+button.dataset.gateDetail,{fresh:true})).arrival;draft=null;batch.clear();render()}
      else if(button.hasAttribute('data-gate-next')||button.hasAttribute('data-gate-cancel')){if(operation){message='Nejprve ověř výsledek rozpracovaného uložení.';render();return}draft=null;selected=null;confirmed=null;bankReservation=null;members=[];message='';operation=null;batch.clear();persist();await load()}
      else if(button.dataset.gateFilter){filter=button.dataset.gateFilter;render()}
      else if(button.hasAttribute('data-gate-photo-retry'))await upload();
      else if(button.hasAttribute('data-gate-reconcile'))await reconcile();
      else if(button.hasAttribute('data-gate-export')){const r=await apiRequest(path+'/export');const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='prijezdy-'+eventId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
      else if(button.hasAttribute('data-gate-invitation-retry')){if(operation)return;operation={id:crypto.randomUUID(),revision:data.revision,suffix:'/invitation-retry',method:'POST',body:{arrivalId:confirmed.id}};persist();await sendOperation()}else if(button.dataset.gateBank){bankReservation=button.dataset.gateBank;persist();render()}
    }catch(error){message=error.message;render()}
  }
  function input(e){if(e.target.matches('[data-gate-filter-query]')){query=e.target.value;const pos=e.target.selectionStart;render();const i=root.querySelector('[data-gate-filter-query]');i.focus();i.setSelectionRange(pos,pos);return}if(e.target.closest('[data-gate-form]')){capture();root.querySelector('[data-gate-totals]').innerHTML=moneyPanel();updateInvite()}}
  function change(e){if(e.target.matches('[data-gate-payment-filter]')){paymentFilter=e.target.value;render();return}if(e.target.matches('[data-gate-file]')){if(batch.items.length)batch.clear();batch.add(e.target.files);e.target.value='';return}if(e.target.name==='carId'){capture();root.querySelector('[data-gate-new-car]').hidden=!!draft.carId;void showMedia()}}
  return {mount(node){if(root!==node){root?.removeEventListener('click',click);root?.removeEventListener('submit',submit);root?.removeEventListener('input',input);root?.removeEventListener('change',change);root=node;root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('input',input);root.addEventListener('change',change)}if(root.dataset.gateContext!==key||!root.querySelector('.gate-heading')){render();void load()}},unmount(){stopCamera();sequence++;root?.removeEventListener('click',click);root?.removeEventListener('submit',submit);root?.removeEventListener('input',input);root?.removeEventListener('change',change);root=null},clear(){stopCamera();root?.removeEventListener('click',click);root?.removeEventListener('submit',submit);root?.removeEventListener('input',input);root?.removeEventListener('change',change);batch.clear();try{sessionStorage.removeItem(storage)}catch{}root?.replaceChildren();root=null},load,async openReservation(id){await load();const a=data.arrivals.find(a=>a.reservation_id===id);if(a){confirmed=(await apiRequest(path+'/'+a.id)).arrival;draft=null}else bankReservation=id;render()},async openArrival(id){await load();confirmed=(await apiRequest(path+'/'+id)).arrival;draft=null;render()}};
}
