import {apiRequest,apiUpload} from '../api.js?v=20260924-merch2';
import {adminState} from '../state.js?v=20260924-merch2';
import {esc,date,statusLabel,orderMarkup,bindOrder} from '../../merch/order-view.js?v=20260924-merch2';
import {money,imageSource} from '../../merch/catalog.js?v=20260924-merch2';
import {merchandiseDocuments} from '../../merch/documents.js?v=20260924-merch2';
export function initializeMerch(){
 const panel=document.querySelector('[data-admin-panel="merch"]'),body=panel.querySelector('[data-merch-admin-body]');let tab='orders',page=1,catalog=null,generation=0;
 panel.classList.add('merch-connected');
 const paymentsPanel=document.querySelector('[data-admin-panel="payments"]');
 const sraz=document.createElement('div');sraz.dataset.srazPayments='';while(paymentsPanel.firstChild)sraz.append(paymentsPanel.firstChild);paymentsPanel.append(sraz);
 const paymentTabs=document.createElement('div');paymentTabs.className='merch-actions';paymentTabs.innerHTML='<button type="button" data-finance-tab="sraz" aria-pressed="true">Sraz</button><button type="button" data-finance-tab="merch" aria-pressed="false">Merch</button>';paymentsPanel.prepend(paymentTabs);
 const paymentSlot=document.createElement('div');paymentSlot.className='merch-connected';paymentsPanel.append(paymentSlot);
 const content=document.createElement('div');while(panel.firstChild)content.append(panel.firstChild);panel.append(content);
 const controls=selector=>content.querySelector(selector);
 paymentTabs.addEventListener('click',e=>{const button=e.target.closest('[data-finance-tab]');if(!button)return;const merch=button.dataset.financeTab==='merch';sraz.hidden=merch;paymentTabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(merch){paymentSlot.append(content);tab='orders';controls('[data-merch-order-controls]').hidden=false;void load();}else{panel.append(content);clear();}});
 const request=(path,options)=>apiRequest('/api/admin/merch'+path,options);
 const stateMessage=value=>controls('[data-merch-admin-status]').textContent=value;
 const still=g=>g===generation&&!adminState.denied&&!!adminState.currentUser;
 function clear(){generation++;body.replaceChildren();catalog=null;stateMessage('');}
 async function load(){const g=++generation;body.textContent='Načítám…';try{
  if(tab==='orders'){
   const params=new URLSearchParams({page:String(page),search:controls('[data-merch-search]').value,filter:controls('[data-merch-order-filter]').value});
   const r=await request('/orders?'+params);if(!still(g))return;
   body.innerHTML=`<div class="merch-orders">${r.orders.map(o=>`<button type="button" class="merch-order-card" data-admin-order="${o.id}"><img src="${esc(imageSource(o.snapshot.lines[0]))}" alt=""><span><b>${esc(o.number)} · ${esc(o.snapshot.address.name)}</b><small>VS ${o.variableSymbol} · ${money(o.snapshot.totalMinor)} · ${statusLabel[o.state.status]} · ${statusLabel[o.payment.status]}</small></span></button>`).join('')||'<p>Žádné objednávky v tomto výběru.</p>'}</div><div class="merch-actions"><button class="shop-button" data-orders-prev>←</button><span>Strana ${page}</span><button class="shop-button" data-orders-next ${r.hasMore?'':'disabled'}>→</button></div><div data-admin-order-detail></div>`;
   body.querySelector('[data-orders-prev]').onclick=()=>{page=Math.max(1,page-1);void load();};body.querySelector('[data-orders-next]').onclick=()=>{page++;void load();};
   const orderId=new URL(location.href).searchParams.get('order');if(orderId){const detail=await request('/orders/'+encodeURIComponent(orderId));if(still(g))showOrder(detail.order);}
  }else{catalog=await request('/catalog');if(!still(g))return;if(tab==='products')products();else settings();}
 }catch(error){if(still(g)){body.textContent=error.message;stateMessage('Data nebyla načtena.');}}}
 function showOrder(order){const host=body.querySelector('[data-admin-order-detail]');if(!host)return;host.innerHTML=orderMarkup(order,{admin:true});bindOrder(host,order,{admin:true,request:apiRequest,onChange:showOrder});host.scrollIntoView({block:'start',behavior:'instant'});}
 body.addEventListener('click',async e=>{const b=e.target.closest('[data-admin-order]');if(b){const g=generation;try{const r=await request('/orders/'+b.dataset.adminOrder);if(still(g))showOrder(r.order);}catch(error){stateMessage(error.message);}}});
 content.querySelectorAll('[data-merch-admin-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.merchAdminTab;page=1;controls('[data-merch-order-controls]').hidden=tab!=='orders';void load();});
 controls('[data-merch-search-form]').onsubmit=e=>{e.preventDefault();page=1;void load();};
 function variant(v={id:'',color:'',image:'',sizes:[],priceMinor:null,availability:'unavailable',swatch:'#888888'}){return `<fieldset class="merch-variant-edit"><legend>Varianta</legend><label>Stabilní ID<input name="variantId" value="${esc(v.id)}" required ${v.id?'readonly':''}></label><label>Barva / střih<input name="color" value="${esc(v.color)}" required></label><label>Vzorek barvy<input type="color" name="swatch" value="${esc(v.swatch)}"></label><label>Fotografie<select name="image"><option value="">Vyber fotografii</option>${[...new Set(catalog.products.flatMap(p=>p.variants.map(v=>v.image)).filter(Boolean).concat(v.image||[]))].map(i=>`<option ${i===v.image?'selected':''}>${esc(i)}</option>`).join('')}</select></label><label>Nahrát JPG, PNG, WebP<input type="file" accept="image/jpeg,image/png,image/webp" data-merch-upload></label><label>Velikosti (oddělené čárkou)<input name="sizes" value="${esc(v.sizes.join(', '))}"></label><label>Cena Kč (prázdná = null)<input name="price" type="number" step="0.01" min="0.01" value="${v.priceMinor===null?'':v.priceMinor/100}"></label><label>Dostupnost<select name="availability"><option value="available" ${v.availability==='available'?'selected':''}>Dostupné</option><option value="unavailable" ${v.availability!=='available'?'selected':''}>Nedostupné</option></select></label></fieldset>`;}
 function products(){body.innerHTML=`<div class="merch-actions"><button class="shop-button" data-new-product>Nový produkt</button>${!catalog.products.length?'<button class="shop-button" data-seed-products>Založit schválenou kolekci (6 produktů)</button>':''}</div>${catalog.products.map(p=>`<button type="button" class="merch-order-card" data-edit-product="${esc(p.id)}">${esc(p.name)} · ${esc(p.category)} · ${esc(p.status)}</button>`).join('')}<div data-product-editor></div>`;body.querySelector('[data-new-product]').onclick=()=>editProduct();body.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(catalog.products.find(p=>p.id===b.dataset.editProduct)));body.querySelector('[data-seed-products]')?.addEventListener('click',async()=>{try{await request('/seed',{method:'POST'});await load();}catch(e){stateMessage(e.message);}});}
 function editProduct(p={id:'',name:'',type:'',description:'',category:'',gender:'unisex',position:0,status:'draft',variants:[]}){
  const host=body.querySelector('[data-product-editor]');host.innerHTML=`<form data-product-edit><h3>${p.id?'Upravit produkt':'Nový produkt'}</h3><label>ID<input name="id" value="${esc(p.id)}" required ${p.id?'readonly':''}></label>${[['name','Název'],['type','Krátký podtitulek'],['category','Kategorie'],['description','Popis']].map(([k,l])=>`<label>${l}<input name="${k}" value="${esc(p[k])}" ${['name','category'].includes(k)?'required':''}></label>`).join('')}<label>Střih<select name="gender">${[['men','Pánské'],['women','Dámské'],['unisex','Unisex']].map(([v,l])=>`<option value="${v}" ${p.gender===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Stav<select name="status">${[['draft','Koncept'],['published','Publikováno'],['archived','Archivováno']].map(([v,label])=>`<option value="${v}" ${p.status===v?'selected':''}>${label}</option>`).join('')}</select></label><label>Pořadí<input name="position" type="number" min="0" value="${p.position}"></label><div data-variants>${p.variants.map(variant).join('')||variant()}</div><button class="shop-button" type="button" data-add-variant>+ Varianta</button><button class="shop-button shop-primary">Uložit produkt</button></form>`;
  host.querySelector('[data-add-variant]').onclick=()=>host.querySelector('[data-variants]').insertAdjacentHTML('beforeend',variant());
  host.onchange=async e=>{if(!e.target.matches('[data-merch-upload]')||!e.target.files[0])return;const input=e.target;input.disabled=true;try{const r=await apiUpload('/api/admin/merch/media',input.files[0],{method:'POST'});const select=input.closest('fieldset').querySelector('[name=image]');select.add(new Option(r.image,r.image,true,true));}catch(error){stateMessage(error.message);}finally{input.disabled=false;}};
  host.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),values=Object.fromEntries(f);const variants=[...host.querySelectorAll('fieldset')].map(field=>{const get=k=>field.querySelector(`[name=${k}]`).value;return {id:get('variantId'),color:get('color'),swatch:get('swatch'),image:get('image'),sizes:get('sizes').split(',').map(s=>s.trim()).filter(Boolean),priceMinor:get('price')===''?null:Math.round(Number(get('price'))*100),availability:get('availability')};});e.submitter.disabled=true;try{await request('/products',{method:'PUT',body:{...values,revision:p.revision,position:Number(values.position),variants}});stateMessage('Produkt uložen.');await load();}catch(error){stateMessage(error.message);e.submitter.disabled=false;}};
 }
 function settings(){const s=catalog.settings;
  body.innerHTML=`<p>${catalog.ready?'Objednávání je aktivní.':'Objednávání je pozastavené.'}</p><p>${catalog.missing.map(esc).join(' · ')}</p><form data-merch-settings><label><input name="paused" type="checkbox" ${s.paused?'checked':''}>Pozastavit nové objednávky</label><h3>Prodávající</h3>${Object.entries({name:'Název',street:'Ulice',city:'Obec',postalCode:'PSČ',ico:'IČO',taxStatus:'Daňový status (ověřený)',email:'E-mail',phone:'Telefon'}).map(([k,l])=>`<label>${l}<input name="seller-${k}" value="${esc(s.seller[k])}"></label>`).join('')}<label>Cena dopravy Kč<input name="shipping" type="number" min="0" step="0.01" value="${s.shippingMinor/100}"></label><label>Osobní převzetí<textarea name="pickup">${esc(s.pickupInstructions)}</textarea></label><label>Informace o dodání<textarea name="delivery">${esc(s.deliveryInformation)}</textarea></label><label>Aktivita objednávky (hodiny)<input name="hours" type="number" min="1" max="720" value="${s.activeHours}"></label><label>Potvrzená sleva při 12 bodech (%)<input name="discount" type="number" min="0" max="100" step="0.01" value="${s.discountBasisPoints===null?'':s.discountBasisPoints/100}"></label><p>Body se nákupem neodečítají ani nepřidělují. Prázdná sazba blokuje aktivaci.</p><label>Převzít ověřený netestovací účet z registrací<select name="bankEventId"><option value="">Ponechat uložený účet</option>${adminState.events.map(e=>`<option value="${esc(e.id)}">${esc(e.title||e.year)}</option>`).join('')}</select></label><p>${esc(s.bank?.accountDisplay||'Účet zatím nepotvrzen')}</p><label>Verze podmínek<input name="termsVersion" value="${esc(s.termsVersion)}"></label>${[['terms','Obchodní podmínky'],['shipping','Doprava a platba'],['returns','Reklamace a odstoupení'],['privacy','Osobní údaje']].map(([k,l])=>`<label>${l}<textarea rows="7" name="doc-${k}">${esc(s.documents[k])}</textarea></label>`).join('')}<label><input name="legalApproved" type="checkbox" ${s.legalApproved?'checked':''}>Ověřil jsem provozní údaje a obchodní dokumenty pro ostrý prodej</label><button class="shop-button shop-primary">Uložit nastavení</button></form>`;
  const form=body.querySelector('form'),draftButton=document.createElement('button');draftButton.type='button';draftButton.className='shop-button';draftButton.textContent='Připravit návrh dokumentů z uložených údajů';form.prepend(draftButton);draftButton.onclick=()=>{if(!confirm('Nahradit rozepsané dokumenty návrhem k doplnění a kontrole?'))return;for(const[k,v]of Object.entries(merchandiseDocuments(s)))form.elements['doc-'+k].value=v;form.elements.legalApproved.checked=false;stateMessage('Doplň označené údaje a před aktivací ověř dokumenty.');};
  form.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),get=k=>String(f.get(k)||'');e.submitter.disabled=true;try{await request('/settings',{method:'PUT',body:{revision:catalog.revision,bankEventId:get('bankEventId'),settings:{...s,paused:f.has('paused'),seller:Object.fromEntries(Object.keys(s.seller).map(k=>[k,get('seller-'+k)])),shippingMinor:Math.round(Number(get('shipping'))*100),pickupInstructions:get('pickup'),deliveryInformation:get('delivery'),activeHours:Number(get('hours')),discountBasisPoints:get('discount')===''?null:Math.round(Number(get('discount'))*100),termsVersion:get('termsVersion'),legalApproved:f.has('legalApproved'),documents:Object.fromEntries(['terms','shipping','returns','privacy'].map(k=>[k,get('doc-'+k)]))}}});stateMessage('Nastavení uloženo.');await load();}catch(error){stateMessage(error.message);e.submitter.disabled=false;}};
 }
 window.addEventListener('admin:accesslost',clear);window.addEventListener('admin:viewchange',e=>{panel.append(content);sraz.hidden=false;paymentTabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.financeTab==='sraz')));if(e.detail.view==='merch')void load();else clear();});
 window.addEventListener('admin:merch-open',()=>void load());
 return {load,clear};
}
